// Imported from public/Optional_2026.xlsx (167 records)
export const optionalRetireeRecords = [
  {
    "id": "OPT-2026-001",
    "year": 2026,
    "rank": "PMAJ",
    "name": "JUNARD REGLOS BRIONES",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-002",
    "year": 2026,
    "rank": "PCPT",
    "name": "RAGEMER DAPITO HERMIDILLA",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-003",
    "year": 2026,
    "rank": "PCPT",
    "name": "ROMELITO DOMINGUEZ RAMOS",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-004",
    "year": 2026,
    "rank": "PLT",
    "name": "RUVILIO DALID PAULIN",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-005",
    "year": 2026,
    "rank": "PLT",
    "name": "FILIPINA PECAÑA FLORES",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-006",
    "year": 2026,
    "rank": "PEMS",
    "name": "Rosario Pastor Baldos",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-007",
    "year": 2026,
    "rank": "PEMS",
    "name": "Jonhallyn Mentoy Banta",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-008",
    "year": 2026,
    "rank": "PEMS",
    "name": "Reden Florentino Banta",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-009",
    "year": 2026,
    "rank": "PEMS",
    "name": "Marcos Ortilla Cabanias",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-010",
    "year": 2026,
    "rank": "PEMS",
    "name": "Alsander Raymundo Ecalnir",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "Complete",
    "remarks": "Pension: Forwarded to PRBU dated April 7, 2026",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-011",
    "year": 2026,
    "rank": "PEMS",
    "name": "Herminigilda Lumbres Casauran",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-012",
    "year": 2026,
    "rank": "PEMS",
    "name": "Winnie Gladys Wap Crowther",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-013",
    "year": 2026,
    "rank": "PEMS",
    "name": "Joven Torres Harina",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-014",
    "year": 2026,
    "rank": "PEMS",
    "name": "Jerry Joaquin Hernandez",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-015",
    "year": 2026,
    "rank": "PEMS",
    "name": "Amado Castillo Mantuano",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-016",
    "year": 2026,
    "rank": "PEMS",
    "name": "Prisco Recede Onte, Jr",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-017",
    "year": 2026,
    "rank": "PEMS",
    "name": "Eleanor Bernabeo Pabion",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-018",
    "year": 2026,
    "rank": "PEMS",
    "name": "Allan Calderon Villanueva",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-019",
    "year": 2026,
    "rank": "PCMS",
    "name": "Pepito Del Mundo Alejandro, Jr",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-020",
    "year": 2026,
    "rank": "PCMS",
    "name": "Anne Freda Verdan Arcos",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-021",
    "year": 2026,
    "rank": "PCMS",
    "name": "Sean Gaban Francisco",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-022",
    "year": 2026,
    "rank": "PCMS",
    "name": "Ryan Arellano Pagcaliwagan",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-023",
    "year": 2026,
    "rank": "PSMS",
    "name": "Gerom Solo Divina",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-024",
    "year": 2026,
    "rank": "PSMS",
    "name": "Arlan Ilaya Lozada",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-025",
    "year": 2026,
    "rank": "PSMS",
    "name": "Karlo Angelo Vergara Jamon",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-026",
    "year": 2026,
    "rank": "PSMS",
    "name": "Marvin Alegre Noveno",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-027",
    "year": 2026,
    "rank": "PSMS",
    "name": "Timothy Joseph Rosales Virtucio",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "RHQ",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-028",
    "year": 2026,
    "rank": "PSSG",
    "name": "Julius Ortega Blones",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "RHQ",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-029",
    "year": 2026,
    "rank": "PMSG",
    "name": "Angelo Hernandez Mendoza",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-030",
    "year": 2026,
    "rank": "PMSG",
    "name": "Jesse Flora Soriano",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-031",
    "year": 2026,
    "rank": "PSSG",
    "name": "Aldrin Pupa Boholano",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-032",
    "year": 2026,
    "rank": "PSSG",
    "name": "Bryan Ramos Dadulla",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-033",
    "year": 2026,
    "rank": "PSSG",
    "name": "Jhone Dela Roca Ibañez",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-034",
    "year": 2026,
    "rank": "NUP",
    "name": "Noel Tiquis Solis",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-035",
    "year": 2026,
    "rank": "NUP",
    "name": "Nancy Niala Villanueva",
    "retirementDate": "2026-01-01",
    "retirementDisplay": "January 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-036",
    "year": 2026,
    "rank": "PLT",
    "name": "MARIA LUCILLE DE CASTRO DALALO",
    "retirementDate": "2026-02-01",
    "retirementDisplay": "February 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-037",
    "year": 2026,
    "rank": "PLT",
    "name": "MAGDALENA ALUAN VALDEZ",
    "retirementDate": "2026-02-01",
    "retirementDisplay": "February 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-038",
    "year": 2026,
    "rank": "PEMS",
    "name": "Marife Deinla Baes",
    "retirementDate": "2026-02-01",
    "retirementDisplay": "February 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-039",
    "year": 2026,
    "rank": "PEMS",
    "name": "Walter Barairo Castillo",
    "retirementDate": "2026-02-01",
    "retirementDisplay": "February 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-040",
    "year": 2026,
    "rank": "PEMS",
    "name": "Herbart Ugay Dapitanon",
    "retirementDate": "2026-02-01",
    "retirementDisplay": "February 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-041",
    "year": 2026,
    "rank": "PEMS",
    "name": "Reynaldo Briones Red",
    "retirementDate": "2026-02-01",
    "retirementDisplay": "February 01, 2026",
    "unit": "RHQ",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-042",
    "year": 2026,
    "rank": "PSMS",
    "name": "Valiant Malaluan Aguilera",
    "retirementDate": "2026-02-01",
    "retirementDisplay": "February 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-043",
    "year": 2026,
    "rank": "PSMS",
    "name": "Nur Uddin Baladji",
    "retirementDate": "2026-02-01",
    "retirementDisplay": "February 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-044",
    "year": 2026,
    "rank": "PSMS",
    "name": "George Cainglet Ulzame",
    "retirementDate": "2026-02-01",
    "retirementDisplay": "February 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-045",
    "year": 2026,
    "rank": "PMSG",
    "name": "Reynan Maraan Amparo",
    "retirementDate": "2026-02-01",
    "retirementDisplay": "February 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-046",
    "year": 2026,
    "rank": "PMSG",
    "name": "Richmond Diño Anico",
    "retirementDate": "2026-02-01",
    "retirementDisplay": "February 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-047",
    "year": 2026,
    "rank": "PMSG",
    "name": "Edilberto Teves Ballar, Jr",
    "retirementDate": "2026-02-01",
    "retirementDisplay": "February 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-048",
    "year": 2026,
    "rank": "PSSG",
    "name": "Pepito Aguila Abrencillo, Jr",
    "retirementDate": "2026-02-01",
    "retirementDisplay": "February 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-049",
    "year": 2026,
    "rank": "PSSG",
    "name": "Carolin Mingoa Bance",
    "retirementDate": "2026-02-01",
    "retirementDisplay": "February 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-050",
    "year": 2026,
    "rank": "PSSG",
    "name": "Randy Siwagan Manaog",
    "retirementDate": "2026-02-01",
    "retirementDisplay": "February 01, 2026",
    "unit": "RHQ",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-051",
    "year": 2026,
    "rank": "PSSG",
    "name": "Roel Ricafrente Parin",
    "retirementDate": "2026-02-01",
    "retirementDisplay": "February 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-052",
    "year": 2026,
    "rank": "PMAJ",
    "name": "EUGENIO NEPTHALI ESGUERRA SOLOMON",
    "retirementDate": "2026-03-01",
    "retirementDisplay": "March 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-053",
    "year": 2026,
    "rank": "PCPT",
    "name": "ALBERT ALFONSO QUINTO AYOSO",
    "retirementDate": "2026-03-01",
    "retirementDisplay": "March 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-054",
    "year": 2026,
    "rank": "PLT",
    "name": "CELEDONIO LIGGAYU DE ASIS",
    "retirementDate": "2026-03-01",
    "retirementDisplay": "March 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-055",
    "year": 2026,
    "rank": "PLT",
    "name": "CARYN CABALI MANALAD",
    "retirementDate": "2026-03-01",
    "retirementDisplay": "March 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-056",
    "year": 2026,
    "rank": "PEMS",
    "name": "Juanito Austria Alolod, Jr",
    "retirementDate": "2026-03-01",
    "retirementDisplay": "March 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-057",
    "year": 2026,
    "rank": "PEMS",
    "name": "Pio Pievro Bucado Avila",
    "retirementDate": "2026-03-01",
    "retirementDisplay": "March 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-058",
    "year": 2026,
    "rank": "PEMS",
    "name": "Lorna Hilario Baird",
    "retirementDate": "2026-03-01",
    "retirementDisplay": "March 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-059",
    "year": 2026,
    "rank": "PEMS",
    "name": "Patricio Anquilo Dino",
    "retirementDate": "2026-03-01",
    "retirementDisplay": "March 01, 2026",
    "unit": "RHQ",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-060",
    "year": 2026,
    "rank": "PEMS",
    "name": "Ruel Veluya Julia",
    "retirementDate": "2026-03-01",
    "retirementDisplay": "March 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-061",
    "year": 2026,
    "rank": "PEMS",
    "name": "Liza Abarico Lorena",
    "retirementDate": "2026-03-01",
    "retirementDisplay": "March 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-062",
    "year": 2026,
    "rank": "PEMS",
    "name": "Rodelin Toledo Manalo",
    "retirementDate": "2026-03-01",
    "retirementDisplay": "March 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-063",
    "year": 2026,
    "rank": "PCMS",
    "name": "Dadeth Lubay Roadilla",
    "retirementDate": "2026-03-01",
    "retirementDisplay": "March 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-064",
    "year": 2026,
    "rank": "PSSG",
    "name": "Gessel Discutido Gondra",
    "retirementDate": "2026-03-01",
    "retirementDisplay": "March 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-065",
    "year": 2026,
    "rank": "PSSG",
    "name": "Dennis Cruz Reyes",
    "retirementDate": "2026-03-01",
    "retirementDisplay": "March 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-066",
    "year": 2026,
    "rank": "PCPL",
    "name": "Diony Cataje Alikpala, Jr",
    "retirementDate": "2026-03-01",
    "retirementDisplay": "March 01, 2026",
    "unit": "RMFB 4A",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-067",
    "year": 2026,
    "rank": "PEMS",
    "name": "Archie Tabalan Alvarado",
    "retirementDate": "2026-04-01",
    "retirementDisplay": "April 01, 2026",
    "unit": "RHQ",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-068",
    "year": 2026,
    "rank": "PEMS",
    "name": "Jovy Avenilla Bautista",
    "retirementDate": "2026-04-01",
    "retirementDisplay": "April 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-069",
    "year": 2026,
    "rank": "PEMS",
    "name": "Antonio Suarez Ermita",
    "retirementDate": "2026-04-01",
    "retirementDisplay": "April 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-070",
    "year": 2026,
    "rank": "PEMS",
    "name": "Emmylou Bentir Ermita",
    "retirementDate": "2026-04-01",
    "retirementDisplay": "April 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-071",
    "year": 2026,
    "rank": "PEMS",
    "name": "Rodel Navarro Mina",
    "retirementDate": "2026-04-01",
    "retirementDisplay": "April 01, 2026",
    "unit": "RHQ",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-072",
    "year": 2026,
    "rank": "PEMS",
    "name": "Victor Ornales Tampis",
    "retirementDate": "2026-04-01",
    "retirementDisplay": "April 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-073",
    "year": 2026,
    "rank": "PCMS",
    "name": "Marvin John Catindig Mangahis",
    "retirementDate": "2026-04-01",
    "retirementDisplay": "April 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-074",
    "year": 2026,
    "rank": "PSMS",
    "name": "Verly Malimban Pabiton",
    "retirementDate": "2026-04-01",
    "retirementDisplay": "April 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-075",
    "year": 2026,
    "rank": "PMSG",
    "name": "Rolando Concepcion Samortin, Jr",
    "retirementDate": "2026-04-01",
    "retirementDisplay": "April 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-076",
    "year": 2026,
    "rank": "PMSG",
    "name": "Rolando Cabriza Crisostomo III",
    "retirementDate": "2026-04-01",
    "retirementDisplay": "April 01, 2026",
    "unit": "RMFB 4A",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-077",
    "year": 2026,
    "rank": "PMSG",
    "name": "Gerardo Mueco Talatala",
    "retirementDate": "2026-04-01",
    "retirementDisplay": "April 01, 2026",
    "unit": "RMFB 4A",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-078",
    "year": 2026,
    "rank": "PCPL",
    "name": "Milo Vic De Vera Faustino",
    "retirementDate": "2026-04-01",
    "retirementDisplay": "April 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-079",
    "year": 2026,
    "rank": "PAT",
    "name": "Cristina Anciado Ponce",
    "retirementDate": "2026-04-01",
    "retirementDisplay": "April 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-080",
    "year": 2026,
    "rank": "PCPT",
    "name": "RONALD PANES PAGAYON",
    "retirementDate": "2026-05-01",
    "retirementDisplay": "May 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-081",
    "year": 2026,
    "rank": "PLT",
    "name": "JOEVET CORTEZA BELGICA",
    "retirementDate": "2026-05-01",
    "retirementDisplay": "May 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-082",
    "year": 2026,
    "rank": "PEMS",
    "name": "Margieriel Duran Ebol",
    "retirementDate": "2026-05-01",
    "retirementDisplay": "May 01, 2026",
    "unit": "RHQ",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-083",
    "year": 2026,
    "rank": "PEMS",
    "name": "Me Thu Jael Vito Landicho",
    "retirementDate": "2026-05-01",
    "retirementDisplay": "May 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-084",
    "year": 2026,
    "rank": "PEMS",
    "name": "Levi Glenn Tibayan Panganiban",
    "retirementDate": "2026-05-01",
    "retirementDisplay": "May 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-085",
    "year": 2026,
    "rank": "PSMS",
    "name": "Barnie Palma Belotendos",
    "retirementDate": "2026-05-01",
    "retirementDisplay": "May 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-086",
    "year": 2026,
    "rank": "PSMS",
    "name": "Florante Maltu Cabansag",
    "retirementDate": "2026-05-01",
    "retirementDisplay": "May 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-087",
    "year": 2026,
    "rank": "PSMS",
    "name": "Rino Escala Caringal",
    "retirementDate": "2026-05-01",
    "retirementDisplay": "May 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-088",
    "year": 2026,
    "rank": "PLTCOL",
    "name": "FERDINAND BAYAWA ANCHETA",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-089",
    "year": 2026,
    "rank": "PLT",
    "name": "ANNA LUCILLA ANGUSTIA ALLADO",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-090",
    "year": 2026,
    "rank": "PLT",
    "name": "ELLEN MANSION PANOY",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-091",
    "year": 2026,
    "rank": "PLT",
    "name": "MICHAEL ROLDAN PANOY",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-092",
    "year": 2026,
    "rank": "PEMS",
    "name": "Elvis Buizon Mariquina",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "RHQ",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-093",
    "year": 2026,
    "rank": "PEMS",
    "name": "Ameil Bereña Catena",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-094",
    "year": 2026,
    "rank": "PEMS",
    "name": "Michael Hablo Clataro",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-095",
    "year": 2026,
    "rank": "PEMS",
    "name": "Edwin Perez Daño",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-096",
    "year": 2026,
    "rank": "PEMS",
    "name": "Ma. Perla Huertas Dela Peña",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-097",
    "year": 2026,
    "rank": "PEMS",
    "name": "Rogelio Lacbay Magsino",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-098",
    "year": 2026,
    "rank": "PEMS",
    "name": "Arthur Cañaveral Fausto",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-099",
    "year": 2026,
    "rank": "PEMS",
    "name": "Ricardo Pasco Mutas",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "RHQ",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-100",
    "year": 2026,
    "rank": "PCMS",
    "name": "Ronald Dulce Eguia",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-101",
    "year": 2026,
    "rank": "PCMS",
    "name": "Alex Lalusin Matibag",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "RMFB 4A",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-102",
    "year": 2026,
    "rank": "PCMS",
    "name": "Benedict Harold Santos Orfanel",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-103",
    "year": 2026,
    "rank": "PSMS",
    "name": "Shared Basa Decena",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-104",
    "year": 2026,
    "rank": "PSMS",
    "name": "Ronaldo Manzolim Lazaro",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-105",
    "year": 2026,
    "rank": "PMSG",
    "name": "Rene Basco Bibon",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-106",
    "year": 2026,
    "rank": "PMSG",
    "name": "Joan Agustin Durian",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-107",
    "year": 2026,
    "rank": "PMSG",
    "name": "Edwin Mojado Navarro",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-108",
    "year": 2026,
    "rank": "PSSG",
    "name": "Joseph Balmes Busa",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-109",
    "year": 2026,
    "rank": "PSSG",
    "name": "Jay-r Gumpal Gumarang",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-110",
    "year": 2026,
    "rank": "PSSG",
    "name": "Victor Hulpo Montes, Jr",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-111",
    "year": 2026,
    "rank": "PSSG",
    "name": "Charilu Baligod Salazar",
    "retirementDate": "2026-06-01",
    "retirementDisplay": "June 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-112",
    "year": 2026,
    "rank": "PLT",
    "name": "MARIBEL ROMERO SORILLA",
    "retirementDate": "2026-07-01",
    "retirementDisplay": "July 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-113",
    "year": 2026,
    "rank": "PEMS",
    "name": "Nelson Silva Jaen",
    "retirementDate": "2026-07-01",
    "retirementDisplay": "July 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-114",
    "year": 2026,
    "rank": "PEMS",
    "name": "Arcadio Pilit Mendoza",
    "retirementDate": "2026-07-01",
    "retirementDisplay": "July 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-115",
    "year": 2026,
    "rank": "PEMS",
    "name": "Jonathan Platon Manalo",
    "retirementDate": "2026-07-01",
    "retirementDisplay": "July 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-116",
    "year": 2026,
    "rank": "PEMS",
    "name": "Renante Ablitado Peniero",
    "retirementDate": "2026-07-01",
    "retirementDisplay": "July 01, 2026",
    "unit": "RHQ",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-117",
    "year": 2026,
    "rank": "PCMS",
    "name": "Ferdinand Dequina Elardo",
    "retirementDate": "2026-07-01",
    "retirementDisplay": "July 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-118",
    "year": 2026,
    "rank": "PMSG",
    "name": "Eugenio Dalisat Supetran",
    "retirementDate": "2026-07-01",
    "retirementDisplay": "July 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-119",
    "year": 2026,
    "rank": "NUP",
    "name": "Maximina Clarete Apolito",
    "retirementDate": "2026-07-01",
    "retirementDisplay": "July 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-120",
    "year": 2026,
    "rank": "PMAJ",
    "name": "ALICE YUZON ATIENZA",
    "retirementDate": "2026-08-01",
    "retirementDisplay": "August 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-121",
    "year": 2026,
    "rank": "PEMS",
    "name": "Mark Christopher Garcia Aala",
    "retirementDate": "2026-08-01",
    "retirementDisplay": "August 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-122",
    "year": 2026,
    "rank": "PEMS",
    "name": "Myra Raca Cabuyao",
    "retirementDate": "2026-08-01",
    "retirementDisplay": "August 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-123",
    "year": 2026,
    "rank": "PEMS",
    "name": "Christian Atas Caguimbal",
    "retirementDate": "2026-08-01",
    "retirementDisplay": "August 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-124",
    "year": 2026,
    "rank": "PEMS",
    "name": "Roderick Saldivia Formaran",
    "retirementDate": "2026-08-01",
    "retirementDisplay": "August 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-125",
    "year": 2026,
    "rank": "PEMS",
    "name": "Marilou De Chavez Landicho",
    "retirementDate": "2026-08-01",
    "retirementDisplay": "August 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-126",
    "year": 2026,
    "rank": "PEMS",
    "name": "Alvin Oliveros Ramos",
    "retirementDate": "2026-08-01",
    "retirementDisplay": "August 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-127",
    "year": 2026,
    "rank": "PEMS",
    "name": "Diosdado Reyes Ramos",
    "retirementDate": "2026-08-01",
    "retirementDisplay": "August 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-128",
    "year": 2026,
    "rank": "PCMS",
    "name": "Michael Malaiba Banaag",
    "retirementDate": "2026-08-01",
    "retirementDisplay": "August 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-129",
    "year": 2026,
    "rank": "PCMS",
    "name": "Joefrey Mangubat Mendoza",
    "retirementDate": "2026-08-01",
    "retirementDisplay": "August 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-130",
    "year": 2026,
    "rank": "PCMS",
    "name": "Marijin Gimena Mendoza",
    "retirementDate": "2026-08-01",
    "retirementDisplay": "August 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-131",
    "year": 2026,
    "rank": "PCMS",
    "name": "Ferdinand Aureus Pasajol",
    "retirementDate": "2026-08-01",
    "retirementDisplay": "August 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-132",
    "year": 2026,
    "rank": "PSSG",
    "name": "Ferdinand Salvilla Faltado",
    "retirementDate": "2026-08-01",
    "retirementDisplay": "August 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-133",
    "year": 2026,
    "rank": "PPCT",
    "name": "JOSEPH RIVERO POSTRADO",
    "retirementDate": "2026-09-01",
    "retirementDisplay": "September 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-134",
    "year": 2026,
    "rank": "PEMS",
    "name": "Mark Joseph Laureles Flores",
    "retirementDate": "2026-09-01",
    "retirementDisplay": "September 01, 2026",
    "unit": "RHQ",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-135",
    "year": 2026,
    "rank": "PEMS",
    "name": "Rafael Guerrero Salumbides",
    "retirementDate": "2026-09-01",
    "retirementDisplay": "September 01, 2026",
    "unit": "RHQ",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-136",
    "year": 2026,
    "rank": "PEMS",
    "name": "Merrian Sangalang Daño",
    "retirementDate": "2026-09-01",
    "retirementDisplay": "September 01, 2026",
    "unit": "RHQ",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-137",
    "year": 2026,
    "rank": "PEMS",
    "name": "Roger Tanallon Tanamal",
    "retirementDate": "2026-09-01",
    "retirementDisplay": "September 01, 2026",
    "unit": "RHQ",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-138",
    "year": 2026,
    "rank": "PSSG",
    "name": "Bienvenido Lontok Vizcarra",
    "retirementDate": "2026-09-01",
    "retirementDisplay": "September 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-139",
    "year": 2026,
    "rank": "PSMS",
    "name": "Anna Theresa Legaspi Orjalo",
    "retirementDate": "2026-09-01",
    "retirementDisplay": "September 01, 2026",
    "unit": "RHQ",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-140",
    "year": 2026,
    "rank": "PEMS",
    "name": "Edlar Luistro Belen",
    "retirementDate": "2026-10-01",
    "retirementDisplay": "October 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-141",
    "year": 2026,
    "rank": "PEMS",
    "name": "Renie Manzo Malveda",
    "retirementDate": "2026-10-01",
    "retirementDisplay": "October 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-142",
    "year": 2026,
    "rank": "PEMS",
    "name": "Ruby Laloma Reyes",
    "retirementDate": "2026-10-01",
    "retirementDisplay": "October 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-143",
    "year": 2026,
    "rank": "PSMS",
    "name": "Noel Lacro Clarito",
    "retirementDate": "2026-10-01",
    "retirementDisplay": "October 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-144",
    "year": 2026,
    "rank": "PEMS",
    "name": "Alfonso Alvin Reglos Ebite",
    "retirementDate": "2026-11-01",
    "retirementDisplay": "November 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-145",
    "year": 2026,
    "rank": "PEMS",
    "name": "Loida Anicete Geronimo",
    "retirementDate": "2026-11-01",
    "retirementDisplay": "November 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-146",
    "year": 2026,
    "rank": "PEMS",
    "name": "Peter Pedro Alfaro Janairo III",
    "retirementDate": "2026-11-01",
    "retirementDisplay": "November 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-147",
    "year": 2026,
    "rank": "PEMS",
    "name": "Jessie Gordonas Salado",
    "retirementDate": "2026-11-01",
    "retirementDisplay": "November 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-148",
    "year": 2026,
    "rank": "PSMS",
    "name": "Ariel Mendoza Delmoro",
    "retirementDate": "2026-11-01",
    "retirementDisplay": "November 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-149",
    "year": 2026,
    "rank": "PSMS",
    "name": "Elmer Reyes Reyes",
    "retirementDate": "2026-11-01",
    "retirementDisplay": "November 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-150",
    "year": 2026,
    "rank": "PSSG",
    "name": "Lourdes Doclisen Janairo",
    "retirementDate": "2026-11-01",
    "retirementDisplay": "November 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-151",
    "year": 2026,
    "rank": "PSSG",
    "name": "Russell Charles Zapata Himongala",
    "retirementDate": "2026-11-01",
    "retirementDisplay": "November 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-152",
    "year": 2026,
    "rank": "PSSG",
    "name": "Rommel Mojares Lumbera 150624",
    "retirementDate": "2026-11-01",
    "retirementDisplay": "November 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-153",
    "year": 2026,
    "rank": "PSSG",
    "name": "Simplicio Seco Verzo Jr",
    "retirementDate": "2026-11-01",
    "retirementDisplay": "November 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-154",
    "year": 2026,
    "rank": "PCOL",
    "name": "FRANCISCO J LUCEÑA III",
    "retirementDate": "2026-12-01",
    "retirementDisplay": "December 01, 2026",
    "unit": "RHQ",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-155",
    "year": 2026,
    "rank": "PMAJ",
    "name": "DANILO OPINTOR MERCADO",
    "retirementDate": "2026-12-01",
    "retirementDisplay": "December 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-156",
    "year": 2026,
    "rank": "PLT",
    "name": "RONALD LAZONA BANOGBANOG",
    "retirementDate": "2026-12-01",
    "retirementDisplay": "December 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-157",
    "year": 2026,
    "rank": "PEMS",
    "name": "Elmer Onia Cabrera",
    "retirementDate": "2026-12-01",
    "retirementDisplay": "December 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-158",
    "year": 2026,
    "rank": "PEMS",
    "name": "Crispin Laforga Rana",
    "retirementDate": "2026-12-01",
    "retirementDisplay": "December 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-159",
    "year": 2026,
    "rank": "PEMS",
    "name": "Isabelo Guerrero Singuencia II",
    "retirementDate": "2026-12-01",
    "retirementDisplay": "December 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-160",
    "year": 2026,
    "rank": "PEMS",
    "name": "Melody Cacabelos Villanueva",
    "retirementDate": "2026-12-01",
    "retirementDisplay": "December 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-161",
    "year": 2026,
    "rank": "PSMS",
    "name": "Dennis Recalde Dela Vega",
    "retirementDate": "2026-12-01",
    "retirementDisplay": "December 01, 2026",
    "unit": "Batangas PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-162",
    "year": 2026,
    "rank": "PMSG",
    "name": "Sonny Xyrus Cadalig De Leon",
    "retirementDate": "2026-12-01",
    "retirementDisplay": "December 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-163",
    "year": 2026,
    "rank": "PMSG",
    "name": "Tyrone Raymundo Gutierrez",
    "retirementDate": "2026-12-01",
    "retirementDisplay": "December 01, 2026",
    "unit": "Rizal PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-164",
    "year": 2026,
    "rank": "PSSG",
    "name": "Romano Franco Manalo",
    "retirementDate": "2026-12-01",
    "retirementDisplay": "December 01, 2026",
    "unit": "Quezon PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-165",
    "year": 2026,
    "rank": "PSSG",
    "name": "Willie Cabardo Roces",
    "retirementDate": "2026-12-01",
    "retirementDisplay": "December 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-166",
    "year": 2026,
    "rank": "PSSG",
    "name": "Jerwin Seco Verzo",
    "retirementDate": "2026-12-01",
    "retirementDisplay": "December 01, 2026",
    "unit": "Laguna PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  },
  {
    "id": "OPT-2026-167",
    "year": 2026,
    "rank": "NUP",
    "name": "Jonathan Esteban Agcaoili",
    "retirementDate": "2026-12-01",
    "retirementDisplay": "December 01, 2026",
    "unit": "Cavite PPO",
    "calRequirements": "In Process",
    "lumpSumRequirements": "In Process",
    "status": "In Process",
    "remarks": "Optional retirement application filed.",
    "sourceCoverage": "CY 2026 Optional Retirees"
  }
];
