// Generated from the four user-provided final KIPO/WIPO workbooks.
// Source coverage: As of July 6, 2026.
export const seedClaims = [
  {
    "id": "KIPO-2025-001",
    "type": "KIPO",
    "year": 2025,
    "rank": "PMSg",
    "name": "Joel Labajanan Mendoza",
    "province": "Cavite PPO",
    "office": "Carmona CCPS, Cavite PPO",
    "stage": "Document Completion",
    "status": "Pending",
    "date": "2025-07-02",
    "dateDisplay": "July 2, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "",
    "benefits": {
      "pnpSfa": "Received Php347,475.00 on July 2025",
      "cal": "On Process for completion of requirements (processing RSAO clearance with accountability)",
      "promotion": "Not Recommended",
      "awards": "Awarded Medalya ng Kadakilaan (Posthumous) from the CPNP",
      "napolcom": "Submitted documentary requirements to NAPOLCOM Regional Office CALABARZON on January 26, 2026 (for approval of claims) (Approved March 6, 2026 /Approved Cheque June 18, 2026)",
      "psmbfi": "Received Php183,602.10 on July 7, 2025 (initial claim) / Submitted requirements for full claims, waiting for release (Received Full Payment Claim Php 859,196)",
      "psfSfa": "Received Php500,000.00 on December 2025",
      "education": "granted Bayaning Pulis Foundation Educational Assistance Program (SY 2026-2027)",
      "philHealth": "Enrolled",
      "others": "Received Financial Assistance from RD, PRO 4A (Php50,000.00); PD, Cavite PPO (Php20,000.00); Cavite PPO (Php229,590.00); Carmona LGU paid hospitalization expenses (Php58,400.00); Congressman Loyola (Php20,000.00); Carmona CCPS (Php37,000.00); PRO 4A Tulungan (Php80,000.00)"
    }
  },
  {
    "id": "KIPO-2025-002",
    "type": "KIPO",
    "year": 2025,
    "rank": "PSSg",
    "name": "Aldwin Lusterio Jamilla",
    "province": "Laguna PPO",
    "office": "Pagsanjan MPS, Laguna PPO",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2025-11-16",
    "dateDisplay": "November 16, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "",
    "benefits": {
      "pnpSfa": "Received Php337,448.00 on December 2, 2025",
      "cal": "Submitted documentary requirements to PRBU 4A on May 5, 2026 (on process)",
      "promotion": "Not Recommended",
      "awards": "Awarded Medalya ng Kadakilaan (Posthumous)",
      "napolcom": "Submitted documentary requirements to NAPOLCOM 4A on March 6, 2026 (additional documents from beneficiaries were submitted on May 4, 2026) (Approved May 21, 2026 waiting for the release of funds)",
      "psmbfi": "Received Php109,450.00 on July 20, 2025 (initial claim) / Submitted requirements for full claims, waiting for release (Received Full Payment Claim Php 1,010,949.04)",
      "psfSfa": "Received Php500,000.00 on February 25, 2026",
      "education": "granted Bayaning Pulis Foundation Educational Assistance Program (SY 2026-2027)",
      "philHealth": "Enrolled",
      "others": "Received Financial Assistance from RD, PRO 4A (Php50,000.00); PD, Laguna PPO (Php15,000.00); PRO 4A Tulungan (Php80,000.00); Pagsanjan Mayor (Php25,000.00); Laguna Governor (Php5,000.00)"
    }
  },
  {
    "id": "KIPO-2025-003",
    "type": "KIPO",
    "year": 2025,
    "rank": "Pat",
    "name": "Ronn Jay Molines Chavez",
    "province": "Quezon PPO",
    "office": "QPMFC, Quezon PPO",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2025-12-19",
    "dateDisplay": "December 19, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "",
    "benefits": {
      "pnpSfa": "Received Php256,796.00 on December 26, 2025",
      "cal": "Submitted documentary requirements to PRBU 4A on May 5, 2026 (on process)",
      "promotion": "Recommended for Special Promotion (Posthumous)",
      "awards": "Awarded Medalya ng Kadakilaan (Posthumous)",
      "napolcom": "Submitted documentary requirements to NAPOLCOM 4A on April 30, 2026 (for evaluation and approval of claims) (For processing NAPOLCO M 4A)",
      "psmbfi": "Received Php347,726.05 on December 21, 2025 (initial claim) / Submitted requirements for full claims, waiting for release (Received Full Payment Claim Php 792,328.23)",
      "psfSfa": "Received Php500,000.00 on March 4, 2026",
      "education": "No qualified dependent",
      "philHealth": "Enrolled",
      "others": "Received Financial Assistance from ACPNP (Php300,000.00); from RD, PRO 4A (Php50,000.00); PD, Quezon PPO (Php50,000.00); PRO 4A Tulungan (Php80,000.00); FC, QPMFC (Php5,000.00); Quezon PPO personnel (Php35,050.00)"
    }
  },
  {
    "id": "KIPO-2026-001",
    "type": "KIPO",
    "year": 2026,
    "rank": "PCpl",
    "name": "Ryan Onia Vizmanos",
    "province": "Cavite PPO",
    "office": "Carmona CCPS, Cavite PPO",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2026-01-08",
    "dateDisplay": "January 8, 2026 (Died on January 29, 2026)",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "",
    "benefits": {
      "pnpSfa": "Received Php283,711.00 March 5, 2026",
      "cal": "On Process by the designated Survivor Officers and Beneficiaries (processing DL clearance)",
      "promotion": "Not Recommended",
      "awards": "Awarded Medalya ng Kadakilaan (Posthumous)",
      "napolcom": "Processing documentary requirements by the designated Survivor Officers and Beneficiaries to be submitted to NAPOLCOM 4A (waiting for PSA Birth Certificate of new-born Child) (Approved June 10, 2026 waiting for the release of funds)",
      "psmbfi": "Received Php292,343.50 on February 3, 2026 (initial claim) / Submitted requirements for full claims on March 19, 2026, waiting for release (Received Full Payment Claim Php 1,041, 343.50)",
      "psfSfa": "Received Php500,000.00 on May 7, 2026",
      "education": "No qualified dependent",
      "philHealth": "Enrolled",
      "others": "Received Financial Assistance Php60,000.00 from RD, PRO 4A; Php15,000.00 from City Mayor; Php15,000.00 from Vice Mayor; Php70,000.00 from PRO 4A Tulungan; Php250,000.00 from Cavite PPO personnel; Php238,000.00 from Cavite PPO Tulungan; Php10,000.00 from COP, Gen Tri CCPS; Funeral Service worth Php63,000.00 paid by GenTri CCPS; Hospitalization worth Php210,000.00 paid by LGU"
    }
  },
  {
    "id": "KIPO-2026-002",
    "type": "KIPO",
    "year": 2026,
    "rank": "PCMS",
    "name": "George Norada Amazona",
    "province": "Cavite PPO",
    "office": "Carmona CCPS, Cavite PPO",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2026-02-14",
    "dateDisplay": "February 14, 2026",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "",
    "benefits": {
      "pnpSfa": "Received Php378,059.34",
      "cal": "On Process by the designated Survivor Officers and Beneficiaries (processing DL and DC clearances)",
      "promotion": "Not Recommended",
      "awards": "Not Entitled",
      "napolcom": "Processing documentary requirements by the designated Survivor Officers and Beneficiaries to be submitted to NAPOLCOM 4A (processing PNP clearances and PSA documents) (Ongoing Investigation NAPOLCOM 4A)",
      "psmbfi": "Receivec Php128,350.00 (initial claim)",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM and subsequently to OUSPO, DILG on February 16, 2026 (waiting for release of claims)",
      "education": "granted Bayaning Pulis Foundation Educational Assistance Program (SY 2026-2027)",
      "philHealth": "Enrolled",
      "others": "Received Financial Assistance: Php40,000.00 from RD, PRO 4A; Php70,000 from PRO 4A Tulungan; Php10,000.00 from PD, QPPO; Php49,800.00 and Php90,850.00 and Php105,950.00 from Personnel of Quezon PPO; Php23,000.00 from Catanauan MPS;"
    }
  },
  {
    "id": "KIPO-2026-003",
    "type": "KIPO",
    "year": 2026,
    "rank": "PMSg",
    "name": "Jeffrey Pecayo Lopega",
    "province": "Cavite PPO",
    "office": "Carmona CCPS, Cavite PPO",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2026-02-15",
    "dateDisplay": "February 15, 2026",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "",
    "benefits": {
      "pnpSfa": "Received Php365,449.28 March 10, 2026",
      "cal": "On Process by the designated Survivor Officers and Beneficiaries (processing DL clearance)",
      "promotion": "Not Recommended",
      "awards": "Not Entitled",
      "napolcom": "Processing documentary requirements by the designated Survivor Officers and Beneficiaries to be submitted to NAPOLCOM 4A (waiting for PSA Death Certificate) (Ongoing Investigation NAPOLCOM 4A)",
      "psmbfi": "Receive Php109,450.00 (initial claim) / Submitted requirements for full claims, waiting for release (Received Full Payment Claim Php 1, 300,00)",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM and subsequently to OUSPO, DILG on February 18, 2026 (waiting for release of claims)",
      "education": "No qualified dependent",
      "philHealth": "Enrolled",
      "others": "Received Financial Assistance: Php100,000.00 from Mayor of Taytay; Php40,000.00 from RD, PRO 4A; Php70,000 from PRO 4A Tulungan; Php20,000.00 from COP; from Php64,100.00 from Taytay MPS; Php50,000.00 from Mr. Wilfon Fu (Taytay Chamber of Commerce); Php10,000.00 from Mr. Wong; Php30,000.00 from Rizal PPO Tulungan;"
    }
  },
  {
    "id": "KIPO-2026-004",
    "type": "KIPO",
    "year": 2026,
    "rank": "PCpl",
    "name": "Anthony John Martinez Sison",
    "province": "RHQ",
    "office": "RPDEU 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2026-07-06",
    "dateDisplay": "July 6, 2026",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "",
    "benefits": {
      "pnpSfa": "To receive Php 331, 186.00 (on process)",
      "cal": "On Process by the designated Survivor Officers and Beneficiaries (processing DL clearance)",
      "promotion": "Recommended for Special Promotion (Posthumous)",
      "awards": "Awarded Medalya ng Kadakilaan (Posthumous)",
      "napolcom": "Processing documentary requirements by the designated Survivor Officers and Beneficiaries to be submitted to NAPOLCOM 4A (waiting for PSA Birth Certificate of new-born Child)",
      "psmbfi": "Receive Php 287,667.60 (initial claim) July 8, 2026 / Submitted requirements for full claims, waiting for release",
      "psfSfa": "Processing documentary requirements",
      "education": "",
      "philHealth": "Educational assistance",
      "others": "Received Financial Assistance: Php50,000.00 from RD, PRO 4A; Php70,000 from PRO 4A Tulungan"
    }
  },
  {
    "id": "WIPO-2025-001",
    "type": "WIPO",
    "year": 2025,
    "rank": "PMAJ",
    "name": "JOSEPH IAN CARBONEL JAVA",
    "province": "Quezon PPO",
    "office": "Mulanay MPS, Quezon PPO, PRO 4A",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2025-02-25",
    "dateDisplay": "February 25, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Swelling of Right Hand Dorsal and Tenderness on Right Shoulder",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Received Php5,000.00 on March 24, 2025",
      "psfSfa": "Received Php100,000.00 on September 19, 2025",
      "others": "Received Php5,000.00 from PRO 4A Tulungan"
    }
  },
  {
    "id": "WIPO-2025-002",
    "type": "WIPO",
    "year": 2025,
    "rank": "PEMS",
    "name": "Leonardo Aguilar Mendoza Jr",
    "province": "Quezon PPO",
    "office": "Mulanay MPS, Quezon PPO, PRO 4A",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2025-02-25",
    "dateDisplay": "February 25, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Swelling of Left and Right Thumb",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Received Php5,000.00 on March 24, 2025",
      "psfSfa": "Received Php100,000.00 on September 19, 2025",
      "others": "Received Php5,000.00 from PRO 4A Tulungan"
    }
  },
  {
    "id": "WIPO-2025-003",
    "type": "WIPO",
    "year": 2025,
    "rank": "PSSg",
    "name": "Neil Ian Pico Nieves",
    "province": "Quezon PPO",
    "office": "Mulanay MPS, Quezon PPO, PRO 4A",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2025-02-25",
    "dateDisplay": "February 25, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Bite Mark at Right Hand Dorsal Area, Abrasion at Left Elbow and Left Hand, and Abrasion at Right Foot",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Received Php5,000.00 on March 24, 2025",
      "psfSfa": "Received Php100,000.00 on September 19, 2025",
      "others": "Received Php5,000.00 from PRO 4A Tulungan"
    }
  },
  {
    "id": "WIPO-2025-004",
    "type": "WIPO",
    "year": 2025,
    "rank": "PCpl",
    "name": "Dustin Retuita Delo",
    "province": "Quezon PPO",
    "office": "Mulanay MPS, Quezon PPO, PRO 4A",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2025-02-25",
    "dateDisplay": "February 25, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Lacerated Wound at Left Palm 4th Digit",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Received Php5,000.00 on June 9, 2025",
      "psfSfa": "Received Php100,000.00 on September 19, 2025",
      "others": "Received Php5,000.00 from PRO 4A Tulungan"
    }
  },
  {
    "id": "WIPO-2025-005",
    "type": "WIPO",
    "year": 2025,
    "rank": "Pat",
    "name": "John Cyrille Edrian Pineda De Torres",
    "province": "Quezon PPO",
    "office": "Mulanay MPS, Quezon PPO, PRO 4A",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2025-02-25",
    "dateDisplay": "February 25, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Linear Abrasion at Left Posterior Leg",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Received Php5,000.00 on March 24, 2025",
      "psfSfa": "Received Php100,000.00 on September 19, 2025",
      "others": "Received Php5,000.00 from PRO 4A Tulungan"
    }
  },
  {
    "id": "WIPO-2025-006",
    "type": "WIPO",
    "year": 2025,
    "rank": "Pat",
    "name": "Mark John Mendelivar Perfiñan",
    "province": "Quezon PPO",
    "office": "Mulanay MPS, Quezon PPO, PRO 4A",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2025-02-25",
    "dateDisplay": "February 25, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Lacerated Wound at Left Foot and Right Knee",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Received Php20,000.00 on March 12, 2025",
      "psfSfa": "Received Php100,000.00 on September 19, 2025",
      "others": "Received Php5,000.00 from PRO 4A Tulungan"
    }
  },
  {
    "id": "WIPO-2025-007",
    "type": "WIPO",
    "year": 2025,
    "rank": "PSSg",
    "name": "German Daupan Makahiya",
    "province": "Laguna PPO",
    "office": "SOU, Laguna PPO, PRO 4A",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2025-03-03",
    "dateDisplay": "March 3, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Gunshot Wound Entry Point: Anterior Distal Leg (Right); Exit Point: Posterior Distal Leg (Right); Fracture Distal Tibia Fibula (Right)",
    "benefits": {
      "rhe": "Received Php98,000.00 on December 29, 2025",
      "specialPromotion": "Recommended for Issuance of Higher Awards (For NHQ Board Approval)",
      "awards": "Medalya ng Sugatang Magiting",
      "scholarship": "Not Qualified",
      "psmbfi": "Received Php20,000.00 on March 7, 2025",
      "psfSfa": "Received Php100,000.00 on December 16, 2025",
      "others": "Received Php50,000.00 from RD, PRO4A; Php20,000.00 from DRDO; Php30,000.00 from APD, Laguna PPO; Php10,000.00 from PRO4A Tulungan"
    }
  },
  {
    "id": "WIPO-2025-008",
    "type": "WIPO",
    "year": 2025,
    "rank": "PCpl",
    "name": "Mark Medina Abagon",
    "province": "Rizal PPO",
    "office": "Cainta MPS, Rizal PPO, PRO 4A",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2025-03-12",
    "dateDisplay": "March 12, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Penetrating Injury Secondary to Gunshot Wound, Right Paravertebral; Right Chest",
    "benefits": {
      "rhe": "Availed WIPO Provident Loan / Approve for payment of Php281,532.58",
      "specialPromotion": "Recommended for Issuance of Higher Awards (For NHQ Board Approval)",
      "awards": "Medalya ng Sugatang Magiting",
      "scholarship": "Granted REAP Php30,000.00",
      "psmbfi": "Received Php20,000.00 on March 17, 2025",
      "psfSfa": "Received Php100,000.00 on September 23, 2025",
      "others": "Received Php50,000.00 from RD, PRO4A; Php20,000.00 from DRDO; Php10,000.00 from PD, Rizal PPO; Php10,000.00 from PRO4A Tulungan; Php12,000.00 from Cainta LGU; Php17,000.00 from COP and Cainta MPS personnel; Php5,000.00 from Rizal PPO personnel; Php20,000.00 from PRO 4A Personnel"
    }
  },
  {
    "id": "WIPO-2025-009",
    "type": "WIPO",
    "year": 2025,
    "rank": "PCMS",
    "name": "Crisologo Mangaba Castillo",
    "province": "Quezon PPO",
    "office": "Guinayangan MPS, Quezon PPO",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2025-03-28",
    "dateDisplay": "March 28, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Gunshot Wound, Left Upper Shoulder",
    "benefits": {
      "rhe": "Medical Expenses shouldered by LGU",
      "specialPromotion": "Not Recommended",
      "awards": "Medalya ng Sugatang Magiting and Kagalingan",
      "scholarship": "Granted REAP Php30,000.00",
      "psmbfi": "Received Php20,000.00 on April 7, 2025",
      "psfSfa": "Received Php100,000.00 on September 19, 2025",
      "others": "Received Php30,000.00 from RD, PRO4A; Php10,000.00 from PD, Quezon PPO; Php10,000.00 from PRO 4A Tulungan; Php5,000.00 from Quezon PPO ; Php10,000.00 from Guinayangan MPS; and Php20,300.00 from Class SANDIGAN"
    }
  },
  {
    "id": "WIPO-2025-010",
    "type": "WIPO",
    "year": 2025,
    "rank": "PSSg",
    "name": "John Dammes Pajila Red",
    "province": "PRO 4A",
    "office": "RSOU-RID, PRO 4A (Reassigned to PNP Intelligence Group)",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2025-03-28",
    "dateDisplay": "March 28, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Gunshot Wound, Left Thigh",
    "benefits": {
      "rhe": "Duly informed but did not file (minimal charges were paid)",
      "specialPromotion": "Not Recommended",
      "awards": "Medalya ng Sugatang Magiting and Kagalingan",
      "scholarship": "Transferred to Other Unit",
      "psmbfi": "Received Php20,000.00 on April 7, 2025",
      "psfSfa": "Received Php100,000.00 on September 19, 2025",
      "others": "Received Php30,000.00 from RD, PRO4A; Php10,000.00 from PRO 4A Tulungan"
    }
  },
  {
    "id": "WIPO-2025-011",
    "type": "WIPO",
    "year": 2025,
    "rank": "PSSg",
    "name": "Arnel Guiwagiw Caligtan",
    "province": "Laguna PPO",
    "office": "Majayjay MPS, Laguna PPO (Reassigned to PRO CAR)",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2025-03-30",
    "dateDisplay": "March 30, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Multiple Injuries (Right Face, Left Leg) and bruises on different parts of the body",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Received Php5,000.00 on April 7, 2025",
      "psfSfa": "Received Php100,000.00 on September 19, 2025",
      "others": "Majayjay MPS paid medical expenses; Php10,000.00 from PRO 4A Tulungan"
    }
  },
  {
    "id": "WIPO-2025-012",
    "type": "WIPO",
    "year": 2025,
    "rank": "Pat",
    "name": "Mark Anthony Macatangga Bathan",
    "province": "Batangas PPO",
    "office": "Tanauan CCPS, Batangas PPO, PRO 4A",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2025-06-14",
    "dateDisplay": "June 14, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Fracture on Right Femur, Right Patella",
    "benefits": {
      "rhe": "Availed of WIPO Provident Loan / submitted application folder to RMDU 4A on July 30, 2025 (approved to receive: Php184,861.80)",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Received Php50,000.00 on September 16, 2025",
      "psfSfa": "Received Php100,000.00 on January 13, 2026",
      "others": "Tanauan CCPS shouldered hospital expenses at DMMC; Php3,100 from Tanauan CCPS; Php9,000.00 from Batangas PPO; Php10,000.00 from PRO 4A Tulungan; Php40,000.00 from City Mayor"
    }
  },
  {
    "id": "WIPO-2025-013",
    "type": "WIPO",
    "year": 2025,
    "rank": "Pat",
    "name": "Daniel John Villanueva Resurreccion",
    "province": "Laguna PPO",
    "office": "Biñan CPS, Laguna PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-06-17",
    "dateDisplay": "June 17, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Abrasion, Right Knee",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Medalya ng Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Received Php20,000.00 on June 20, 2025",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on July 7, 2025 (Approved by the NHQ PSF-SFA Committee on July 29, 2025,Batch 103) to receive Php100,000.00 (Office of the President)",
      "others": "Php10,000.00 from PRO 4A Tulungan"
    }
  },
  {
    "id": "WIPO-2025-014",
    "type": "WIPO",
    "year": 2025,
    "rank": "PSSg",
    "name": "Joseph Martin Abrantes Fabula",
    "province": "Cavite PPO",
    "office": "Carmona CCPS, Cavite PPO, PRO 4A",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2025-07-02",
    "dateDisplay": "July 2, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Gunshot Wound, Superficial, Left Leg Anterior Part",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "For recommendation",
      "awards": "Medalya ng Sugatang Magiting and Medalya ng Kadakilaan",
      "scholarship": "For recommendation",
      "psmbfi": "Received Php20,000.00 on July 4, 2025",
      "psfSfa": "Received Php100,000.00 on December 15, 2025",
      "others": "Cavite LGU shouldered medical expenses; Php10,000.00 from PRO 4A Tulungan"
    }
  },
  {
    "id": "WIPO-2025-015",
    "type": "WIPO",
    "year": 2025,
    "rank": "Pat",
    "name": "Renson Meer Celestra",
    "province": "Rizal PPO",
    "office": "Cardona MPS, Rizal PPO",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2025-07-07",
    "dateDisplay": "July 7, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Fracture, Closed, Complete, Displaced Lateral Tibial Plateu Left",
    "benefits": {
      "rhe": "Received Php76,565.00 on March 10, 2026",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Received Php20,000.00 on July 11, 2025",
      "psfSfa": "Received Php100,000.00 on November 2025",
      "others": "Php15,000.00 from PRO 4A Tulungan; Php2,000.00 from COP, Cardona MPS"
    }
  },
  {
    "id": "WIPO-2025-016",
    "type": "WIPO",
    "year": 2025,
    "rank": "PCpl",
    "name": "Dan Aris Villamor Wagan",
    "province": "Batangas PPO",
    "office": "Tanauan CCPS, Batangas PPO, PRO 4A",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2025-08-11",
    "dateDisplay": "August 11, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Multiple Injuries secondary to vehicular accident",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Medalya ng Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Received Php20,000.00 on August 14, 2025",
      "psfSfa": "Received Php100,000.00 on December 15, 2025",
      "others": "Php10,000.00 from PRO 4A Tulungan"
    }
  },
  {
    "id": "WIPO-2025-017",
    "type": "WIPO",
    "year": 2025,
    "rank": "PSSg",
    "name": "Dexter Aldave Toledo",
    "province": "RMFB 4A",
    "office": "RMFB 4A, PRO 4A",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2025-09-21",
    "dateDisplay": "September 21, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Abrasion on Right Leg",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Medalya ng Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Received Php5,000.00 on October 27, 2025",
      "psfSfa": "Received Php100,000.00 on January 20, 2026",
      "others": "Php12,000.00 from RD, PRO 4A; and Php5,000.00 from PRO 4A Tulungan"
    }
  },
  {
    "id": "WIPO-2025-018",
    "type": "WIPO",
    "year": 2025,
    "rank": "PCpl",
    "name": "Allan Paul Ortega Araviso",
    "province": "RMFB 4A",
    "office": "RMFB 4A, PRO 4A",
    "stage": "Benefits Released",
    "status": "Completed",
    "date": "2025-09-21",
    "dateDisplay": "September 21, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Bite Injury on Right Arm",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Medalya ng Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Received Php5,000.00 on October 27, 2025",
      "psfSfa": "Received Php100,000.00 on February 3, 2026",
      "others": "Php12,000.00 from RD, PRO 4A; and Php5,000.00 from PRO 4A Tulungan"
    }
  },
  {
    "id": "WIPO-2025-019",
    "type": "WIPO",
    "year": 2025,
    "rank": "PMAJ",
    "name": "EDGAR FERRER FABREGAS",
    "province": "Batangas PPO",
    "office": "Batangas CCPS, Batangas PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-09-29",
    "dateDisplay": "September 29, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Gushot Wound (Point of Entry: Epigastric Area then Stomach Perforating the Diaphragm, Left; Point of Exit: 9th Intercostal Space, Posterior Axillary Injury to Left, Localized Left Chest",
    "benefits": {
      "rhe": "Submitted documentary requirements to RMDU 4A on November 11, 2025 (approved to receive Php558,745.68)",
      "specialPromotion": "Not Recommended",
      "awards": "Medalya ng Kagitingan and Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Received Php20,000.00 on October 7, 2025; Php30,000.00 on October 24, 2025",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on October 9, 2025 (Approved by of the NHQ PSF-SFA Committee on October 22, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php100,000.00 from RD, PRO 4A; Php15,000.00 from PD, BPPO; Php5,000.00 from PRO 4A Tulungan Php3,000.00 from CESPO, PNP; PhpPhp85,745.68 from Batangas CCPS; Hospitalization assistance from Batangas LGU"
    }
  },
  {
    "id": "WIPO-2025-020",
    "type": "WIPO",
    "year": 2025,
    "rank": "PSSg",
    "name": "Karl Ernest Lacsamana Fabonan",
    "province": "Batangas PPO",
    "office": "Batangas CCPS, Batangas PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-09-29",
    "dateDisplay": "September 29, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Comminuted Fracture and Laceration, Left Hand (Open Fracture)",
    "benefits": {
      "rhe": "Submitted documentary requirements to RMDU 4A on November 11, 2025 (approved to receive Php106,209.65)",
      "specialPromotion": "Not Recommended",
      "awards": "Medalya ng Kagitingan and Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Received Php20,000.00 on October 7, 2025; Php30,000.00 on October 24, 2025",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on October 9, 2025 (Approved by of the NHQ PSF-SFA Committee on October 22, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php50,000.00 from RD, PRO 4A; Php15,000.00 from PD, BPPO; Php5,000.00 from PRO 4A Tulungan; Php3,000.00 from CESPO, PNP; Php296,000.00 from Batangas CCPS personnel; Php88,128.19 from COP, Batangas CCPS Hospitalization assistance from Batangas LGU"
    }
  },
  {
    "id": "WIPO-2025-021",
    "type": "WIPO",
    "year": 2025,
    "rank": "PSSg",
    "name": "Arven Hernandez Ilagan",
    "province": "Batangas PPO",
    "office": "Batangas CCPS, Batangas PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-09-29",
    "dateDisplay": "September 29, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Hypovolemic Shock Secondary to Transection Branchial Artery Leftl Hemoperitoneum secondary to Grade III Grastro Injury; Grade II Liver and Spleen Injury Secondary to Gunshot Wounds",
    "benefits": {
      "rhe": "Submitted documentary requirements to RMDU 4A on November 11, 2025 (approved to receive Php446,628.19)",
      "specialPromotion": "Not Recommended",
      "awards": "Medalya ng Kagitingan and Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Received Php20,000.00 on October 7, 2025 (for approval of major injury)",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on October 9, 2025 (Approved by of the NHQ PSF-SFA Committee on October 22, 2025) to receive to receive Php100,000.00 (Office of the President)",
      "others": "Php50,000.00 from RD, PRO 4A; Php15,000.00 from PD, BPPO; Php5,000.00 from PRO 4A Tulungan; Php3,000.00 from CESPO, PNP; Php56,509.65 from COP, Batangas CCPS Hospitalization assistance from Batangas LGU"
    }
  },
  {
    "id": "WIPO-2025-022",
    "type": "WIPO",
    "year": 2025,
    "rank": "Pat",
    "name": "Raymund John Navarro Dichoso",
    "province": "Rizal PPO",
    "office": "Taytay MPS, Rizal PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-09-29",
    "dateDisplay": "September 29, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Bruise on his left middle finger and Contusion on his right leg",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Recommended for Medalya ng Kabayanihan (for NHQ SPADB Deliberation)",
      "awards": "Medalya ng Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on October 9, 2025 (Approved by of the NHQ PSF-SFA Committee on October 22, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php12,000.00 from RD, PRO 4A; and Php5,000.00 from PRO 4A Tulungan"
    }
  },
  {
    "id": "WIPO-2025-023",
    "type": "WIPO",
    "year": 2025,
    "rank": "PMAJ",
    "name": "EL CID ASEHAN VILLANUEVA",
    "province": "Batangas PPO",
    "office": "Talisay MPS, Batangas PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-10-05",
    "dateDisplay": "October 5, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Muscle skeletal strain, left shoulder secondary to VA r/o fracture; abrasions",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Medalya ng Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Not a Member",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on October 14, 2025 (Approved by of the NHQ PSF-SFA Committee on October 22, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php12,000.00 from RD, PRO 4A; and Php5,000.00 from PRO 4A Tulungan"
    }
  },
  {
    "id": "WIPO-2025-024",
    "type": "WIPO",
    "year": 2025,
    "rank": "Pat",
    "name": "Aristotle Philip Cruz Silva",
    "province": "Rizal PPO",
    "office": "Taytay MPS, Rizal PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-10-10",
    "dateDisplay": "October 10, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Abrasions on Right Thigh, Swelling of Right Arm",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Medalya ng Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on October 21, 2025 (Approved by the NHQ PSF-SFA Committee on November 6, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php12,000.00 from RD, PRO 4A; and Php5,000.00 from PRO 4A Tulungan"
    }
  },
  {
    "id": "WIPO-2025-025",
    "type": "WIPO",
    "year": 2025,
    "rank": "PSSg",
    "name": "Teddy Palaquia Delos Santos, Jr",
    "province": "Cavite PPO",
    "office": "Bacoor CCPS, Cavite PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-10-13",
    "dateDisplay": "October 13, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Laceration 5th Digit, Right Hand (4cm), Multiple Abrasion, Bilateral Knee",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Medalya ng Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on October 24, 2025 (Approved by the NHQ PSF-SFA Committee on November 6, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php5,000.00 from PRO 4A Tulungan"
    }
  },
  {
    "id": "WIPO-2025-026",
    "type": "WIPO",
    "year": 2025,
    "rank": "PCMS",
    "name": "Alberto Romblon Plaza",
    "province": "Laguna PPO",
    "office": "Calamba CCPS, Laguna PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-10-15",
    "dateDisplay": "October 15, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Gunshot Wound on his Right Shoulder",
    "benefits": {
      "rhe": "Submitted documentary requirements to RMDU 4A on December 2, 2025 (approved to receive Php2,637.00)",
      "specialPromotion": "Recommended for Medalya ng Kabayanihan (for NHQ SPADB Deliberation)",
      "awards": "Medalya ng Kagalingan and Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Received Php20,000.00 on October 20, 2025 (for approval of major injury)",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on October 28, 2025 (Approved by the NHQ PSF-SFA Committee on November 6, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php80,000.00 from RD, PRO 4A; Php5,000.00 from PRO 4A Tulungan; and Php20,000.00 from Mayor, Calamba City"
    }
  },
  {
    "id": "WIPO-2025-027",
    "type": "WIPO",
    "year": 2025,
    "rank": "PSSg",
    "name": "John Gocon Principe",
    "province": "Laguna PPO",
    "office": "Calamba CCPS, Laguna PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-10-15",
    "dateDisplay": "October 15, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Gunshot Wound on his Right Leg",
    "benefits": {
      "rhe": "Submitted documentary requirements to RMDU 4A on December 2, 2025 (approved to receive Php2,629.80)",
      "specialPromotion": "Recommended for Medalya ng Kabayanihan (for NHQ SPADB Deliberation)",
      "awards": "Medalya ng Kagalingan and Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Received Php20,000.00 on October 20, 2025 (for approval of major injury)",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on October 28, 2025 (Approved by the NHQ PSF-SFA Committee on November 6, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php50,000.00 from RD, PRO 4A; Php5,000.00 from PRO 4A Tulungan; and Php20,000.00 from Mayor, Calamba City"
    }
  },
  {
    "id": "WIPO-2025-028",
    "type": "WIPO",
    "year": 2025,
    "rank": "Pat",
    "name": "Johnpaulo Diccion Llarena",
    "province": "Batangas PPO",
    "office": "Balayan MPS, Batangas PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-10-19",
    "dateDisplay": "October 19, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "open, complete, displaced, fracture, middle third tibia right",
    "benefits": {
      "rhe": "Submitted documentary requirements to RMDU 4A on January 6, 2026 (for RHE Board Deliberation) Approved to receive Php 75,818.00",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Not a member",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on October 30, 2025 (Approved by of the NHQ PSF-SFA Committee on November 19, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php30,000.00 from RD, PRO 4A; Php20,000.00 from COP, Balayan MPS; Php21,700.00 from Balayan MPS personnel; Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2025-029",
    "type": "WIPO",
    "year": 2025,
    "rank": "Pat",
    "name": "Kenlee Balazon Calapati",
    "province": "Batangas PPO",
    "office": "Balayan MPS, Batangas PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-10-19",
    "dateDisplay": "October 19, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Multiple Physical Injuries",
    "benefits": {
      "rhe": "Out-patient",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on October 30, 2025 (Approved by of the NHQ PSF-SFA Committee on November 19, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2025-030",
    "type": "WIPO",
    "year": 2025,
    "rank": "PMSg",
    "name": "Christopher John Lu Chupeco",
    "province": "Laguna PPO",
    "office": "Calamba CCPS, Laguna PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-10-21",
    "dateDisplay": "October 21, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Gunshot Wound Left Arm",
    "benefits": {
      "rhe": "Submitted documentary requirements to RMDU 4A on December 2, 2025 (for RHE Board Deliberation) Medical expenses paid by LGU",
      "specialPromotion": "Recommended for Medalya ng Kabayanihan (for NHQ SPADB Deliberation)",
      "awards": "Medalya ng Kagalingan and Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Received Php20,000.00 on October 27, 2025",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on October 31, 2025 (Approved by of the NHQ PSF-SFA Committee on November 19, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php30,000.00 from RD, PRO 4A; Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2025-031",
    "type": "WIPO",
    "year": 2025,
    "rank": "PCpl",
    "name": "Ervin Manaog Malibiran",
    "province": "Batangas PPO",
    "office": "Alitagtag MPS, Batangas PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-10-22",
    "dateDisplay": "October 22, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Hematoma, Right Temporal Area; Lacerations, Punctate Right Elbow, Curve Left 5th Finger",
    "benefits": {
      "rhe": "Out-patient",
      "specialPromotion": "Recommended for Medalya ng Kabayanihan (for NHQ SPADB Deliberation)",
      "awards": "Medalya ng Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on October 31, 2025 (Approved by of the NHQ PSF-SFA Committee on November 19, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php12,000.00 from RD, PRO 4A; Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2025-032",
    "type": "WIPO",
    "year": 2025,
    "rank": "PSMS",
    "name": "Allan Gurango Potes",
    "province": "Quezon PPO",
    "office": "Panukulan MPS, Quezon PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-10-27",
    "dateDisplay": "October 27, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Slight Physical Injuries: Abrasion on Left Lumber Region, Lacerated Wound on 5th Digit Right Hand secondary to Mauling",
    "benefits": {
      "rhe": "Out-patient",
      "specialPromotion": "Recommended for Medalya ng Kabayanihan (for NHQ SPADB Deliberation)",
      "awards": "Medalya ng Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on November 6, 2025 (Approved by of the NHQ PSF-SFA Committee on November 19, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php12,000.00 from RD, PRO 4A; and Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2025-033",
    "type": "WIPO",
    "year": 2025,
    "rank": "PEMS",
    "name": "Christopher Tan Asia",
    "province": "Quezon PPO",
    "office": "Calauag MPS, Quezon PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-10-31",
    "dateDisplay": "October 31, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Head Concussion; Multiple Abrasions secondary to MC VA",
    "benefits": {
      "rhe": "Out-patient",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Not Entitled",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on November 12, 2025 (Approved by of the NHQ PSF-SFA Committee on November 19, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2025-034",
    "type": "WIPO",
    "year": 2025,
    "rank": "PSSg",
    "name": "Renier Joseph Visco Camacho",
    "province": "Quezon PPO",
    "office": "Mauban MPS, Quezon PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-11-11",
    "dateDisplay": "November 11, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Multiple Injury Secondary to Restraint Incident (2-3 cm Lineal Abrasion, Media Aspect, Elbow, Left and 1 cm Avulsed Wound 2nd Digit Right Hand)",
    "benefits": {
      "rhe": "Out-patient",
      "specialPromotion": "Not Recommended",
      "awards": "Medalya ng Sugatang Magiting",
      "scholarship": "Not Qualified",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on November 19, 2025 (Approved by of the NHQ PSF-SFA Committee on November 19, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2025-035",
    "type": "WIPO",
    "year": 2025,
    "rank": "Pat",
    "name": "Rustom Manggao Pacilona",
    "province": "Laguna PPO",
    "office": "Pagsanjan MPS, Laguna PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-11-16",
    "dateDisplay": "November 16, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Multiple Physical Injuries",
    "benefits": {
      "rhe": "Out-patient",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on November 21, 2025 (Approved by of the NHQ PSF-SFA Committee on November 19, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2025-036",
    "type": "WIPO",
    "year": 2025,
    "rank": "Pat",
    "name": "Jann Erwin Petate Velarde",
    "province": "Laguna PPO",
    "office": "Pagsanjan MPS, Laguna PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-11-16",
    "dateDisplay": "November 16, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Multiple Physical Injuries",
    "benefits": {
      "rhe": "Out-patient",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on November 21, 2025 (Approved by of the NHQ PSF-SFA Committee on November 19, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2025-037",
    "type": "WIPO",
    "year": 2025,
    "rank": "Pat",
    "name": "Carl Angelo Convocar Dael",
    "province": "Laguna PPO",
    "office": "Calamba CCPS, Laguna PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-11-19",
    "dateDisplay": "November 19, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Deep Lacerated Wound with Flexor Tendon Laceration 2nd Digit Right Foot",
    "benefits": {
      "rhe": "Submitted documentary requirements to RMDU 4A on January 28, 2026 (for RHE Board Adjudication) Approved to receive Php 22,266.00",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Received Php20,000.00 on November 25, 2025",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on November 28, 2025 (Approved by of the NHQ PSF-SFA Committee on November 19, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2025-038",
    "type": "WIPO",
    "year": 2025,
    "rank": "PEMS",
    "name": "Orlando Cequeña Dobra, Jr",
    "province": "Rizal PPO",
    "office": "Binangonan MPS, Rizal PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-11-22",
    "dateDisplay": "November 22, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Multiple Physical Injuries in the Head and Lower Extremities",
    "benefits": {
      "rhe": "Out-patient",
      "specialPromotion": "Not Recommended",
      "awards": "Medalya ng Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on December 2, 2025 (Approved by of the NHQ PSF-SFA Committee on November 19, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2025-039",
    "type": "WIPO",
    "year": 2025,
    "rank": "PMSg",
    "name": "Jaefran Duavit Bernardino",
    "province": "Rizal PPO",
    "office": "Binangonan MPS, Rizal PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-11-22",
    "dateDisplay": "November 22, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Lacerated Wound Lower Extremities",
    "benefits": {
      "rhe": "Out-patient",
      "specialPromotion": "Not Recommended",
      "awards": "Medalya ng Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on December 2, 2025 (Approved by of the NHQ PSF-SFA Committee on November 19, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2025-040",
    "type": "WIPO",
    "year": 2025,
    "rank": "PSSg",
    "name": "Jake Tungawon Dinay-og",
    "province": "Rizal PPO",
    "office": "Rizal PMFC, Rizal PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-11-22",
    "dateDisplay": "November 22, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Abrasion Left Forearm",
    "benefits": {
      "rhe": "Out-patient",
      "specialPromotion": "Not Recommended",
      "awards": "Medalya ng Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on December 2, 2025 (Approved by of the NHQ PSF-SFA Committee on November 19, 2025) to receive Php100,000.00 (Office of the President)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2025-041",
    "type": "WIPO",
    "year": 2025,
    "rank": "PSSg",
    "name": "Eric Gregy Evallar Estrella",
    "province": "Quezon PPO",
    "office": "Lopez MPS, Quezon PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-12-10",
    "dateDisplay": "December 10, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Multiple Abrasions Right Forearm, Mil Swelling and Tenderness upon Palpitation, Right Lower Jaw",
    "benefits": {
      "rhe": "Out-patient",
      "specialPromotion": "Not Recommended",
      "awards": "Medalya ng Sugatang Magiting",
      "scholarship": "For recommendation",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on December 17, 2025 (Approved by the NHQ PSF-SFA Committee on January 13, 2026) to receive Php100,000.00 (Office of the President)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2025-042",
    "type": "WIPO",
    "year": 2025,
    "rank": "PMSg",
    "name": "Sonnie Cabrera Caringal",
    "province": "Quezon PPO",
    "office": "1st Quezon PMFC, Quezon PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-12-19",
    "dateDisplay": "December 19, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Gunshot Wound on Left Flank secondary to shooting incident",
    "benefits": {
      "rhe": "Submitted documentary requirements to RMDU 4A on January 28, 2026 (for RHE Board Adjudication) Approved to receive Php 112, 267.41",
      "specialPromotion": "Recommended for Medalya ng Kabayanihan (for NHQ SPADB Deliberation)",
      "awards": "Medalya ng Sugatang Magiting and Kadakilaan",
      "scholarship": "For recommendation",
      "psmbfi": "Received Php20,000.00 on January 5, 2026",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on December 29, 2025 (Approved by the NHQ PSF-SFA Committee on January 13, 2026) to receive Php100,000.00 (Office of the President)",
      "others": "Php100,000.00 from ACPNP; Php25,000.00 from RD, PRO 4A; and Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2025-043",
    "type": "WIPO",
    "year": 2025,
    "rank": "Pat",
    "name": "Kim Kenneth Sadile Averia",
    "province": "Quezon PPO",
    "office": "2nd PMFC, Quezon PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-12-19",
    "dateDisplay": "December 19, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Gunshot Wound on Left Arm secondary to shooting incident",
    "benefits": {
      "rhe": "Submitted documentary requirements to RMDU 4A on January 28, 2026 (for RHE Board Adjudication) Approved to receive Php 66,334.77",
      "specialPromotion": "Recommended for Medalya ng Kabayanihan (for NHQ SPADB Deliberation)",
      "awards": "Medalya ng Sugatang Magiting and Kadakilaan",
      "scholarship": "For recommendation",
      "psmbfi": "Received Php20,000.00 on January 5, 2026",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on December 29, 2025 (Approved by the NHQ PSF-SFA Committee on January 13, 2026) to receive Php100,000.00 (Office of the President)",
      "others": "Php100,000.00 from ACPNP; Php25,000.00 from RD, PRO 4A; and Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2025-044",
    "type": "WIPO",
    "year": 2025,
    "rank": "Pat",
    "name": "Roi Palomado Joya",
    "province": "Rizal PPO",
    "office": "Taytay MPS, Rizal PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2025-12-30",
    "dateDisplay": "December 30, 2025",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Abrasion on Left Forearm",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on January 9, 2026 (Approved by the NHQ PSF-SFA Committee on February 5, 2026) to receive Php100,000.00 (Office of the President)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2026-001",
    "type": "WIPO",
    "year": 2026,
    "rank": "PSSg",
    "name": "Randy Dibdiben Matias",
    "province": "Laguna PPO",
    "office": "Cavinti MPS, Laguna PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2026-01-25",
    "dateDisplay": "January 25, 2026",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Multiple Physical Injuries (Right Arm and Face)",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Recommended for Medalya ng Kabayanihan (for NHQ SPADB Deliberation)",
      "awards": "Medalya ng Sugatang Magiting and Kagalingan",
      "scholarship": "For recommendation",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on February 2, 2026 (Approved by the NHQ PSF-SFA Committee on February 5, 2026) to receive Php100,000.00 (Office of the President)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2026-002",
    "type": "WIPO",
    "year": 2026,
    "rank": "PSSg",
    "name": "Miguel Siervo Pelito",
    "province": "Cavite PPO",
    "office": "General Mariano Alvarez MPS, Cavite PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2026-01-29",
    "dateDisplay": "January 29, 2026",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Injuries on the back head, around the right eye, and on the different parts of his body.",
    "benefits": {
      "rhe": "Confined at Asia Medic Hospital in Dasmariñas City, Cavite from January 29 to 31, 2026 (medical expenses paid by LGU)",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on February 5, 2026 (Approved by the NHQ PSF-SFA Committee on February 26, 2026) to receive Php100,000.00 (Office of the President)",
      "others": "Php10,000.00 from RD, PRO 4A; and Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2026-003",
    "type": "WIPO",
    "year": 2026,
    "rank": "Pat",
    "name": "Jimbert Rodrigo Dela Cruz",
    "province": "Rizal PPO",
    "office": "Taytay MPS, Rizal PPO",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2026-02-15",
    "dateDisplay": "February 15, 2026",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Injuries on Right Arm and Leg",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Not a Member",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on February 26, 2026 (Approved by the NHQ PSF-SFA Committee on March 11, 2026) to receive Php100,000.00 (Office of the President)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2026-004",
    "type": "WIPO",
    "year": 2026,
    "rank": "PCpl",
    "name": "Marvin Bulan Tungcul",
    "province": "Quezon PPO",
    "office": "Lopez MPS, Quezon PPO, PRO 4A (reassigned to PRO 2)",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2026-02-25",
    "dateDisplay": "February 25, 2026",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Cerebral Concussion with Multiple Avulsed Wound, Facial Area s/o VA",
    "benefits": {
      "rhe": "Confined at Lopez St. Jude General Hospital, Lopez, Quezon from February 25 to 27, 2026 (Did Not Apply)",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on March 5, 2026 (Approved by the NHQ PSF-SFA Committee on March 24, 2026) to receive Php100,000.00 (Office of the President)",
      "others": "Php30,000.00 from RD, PRO 4A; and Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2026-005",
    "type": "WIPO",
    "year": 2026,
    "rank": "Pat",
    "name": "Jaybee Briones Ero",
    "province": "Rizal PPO",
    "office": "Antipolo CCPS, Rizal PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2026-03-14",
    "dateDisplay": "March 14, 2026",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Lacerated Wound on Right Hand and Right Shoulder Joint",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on March 26, 2026 (Approved by the NHQ PSF-SFA Committee on April 14, 2026) to receive Php100,000.00 (DILG)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2026-006",
    "type": "WIPO",
    "year": 2026,
    "rank": "PSSg",
    "name": "Christian Gerald Marpa Siazon",
    "province": "Quezon PPO",
    "office": "Lucena CCPS, Quezon PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2026-03-22",
    "dateDisplay": "March 22, 2026",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Multiple Abrasion secondary to VA r/o Cerebral Concussion",
    "benefits": {
      "rhe": "Confined at Lucena MMG General Hospital, Lucena City, Quezon from March 22, 2026 to April 6, 2026 (for completion of requirements) (Submitted to RMDU 4A June 2, 2026 for Deliberation)",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on April 1, 2026 (Approved by the NHQ PSF-SFA Committee on April 14, 2026) to receive Php100,000.00 (DILG)",
      "others": "Php30,000.00 from RD,PRO 4A; and Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2026-007",
    "type": "WIPO",
    "year": 2026,
    "rank": "PLT",
    "name": "MANUEL TAPIRU DANGUECAN, JR",
    "province": "Rizal PPO",
    "office": "Angono MPS, Rizal PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2026-04-13",
    "dateDisplay": "April 13, 2026",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Multiple Physical Injuries (Right Elbow and Left Pinky Finger)",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on April 21, 2026 (Approved by the NHQ PSF-SFA Committee on May 13, 2026) to receive Php100,000.00 (DILG)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2026-008",
    "type": "WIPO",
    "year": 2026,
    "rank": "PCpl",
    "name": "Ericson Rivera Cabangca",
    "province": "Quezon PPO",
    "office": "Tiaong MPS, Quezon PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2026-04-15",
    "dateDisplay": "April 15, 2026",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "1x1 graze wound secondary to bullet over left deltoid area with redness",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Medalya ng Kadakilaan",
      "scholarship": "For recommendation",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on April 24, 2026 (Approved by the NHQ PSF-SFA Committee on May 13, 2026) to receive Php100,000.00 (DILG)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2026-009",
    "type": "WIPO",
    "year": 2026,
    "rank": "PSSg",
    "name": "Mark Delos Santos",
    "province": "Rizal PPO",
    "office": "Antipolo CCPS, Rizal PPO, PRO 4A",
    "stage": "Document Review",
    "status": "For Review",
    "date": "2026-04-15",
    "dateDisplay": "April 15, 2026",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Burn Injury on Lower Right Leg and Contusion on Lower Left Leg",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on April 23, 2026 (For approval of the NHQ PSF-SFA Committee) (DILG)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2026-010",
    "type": "WIPO",
    "year": 2026,
    "rank": "Pat",
    "name": "John Cyn Tomas Oligo",
    "province": "Rizal PPO",
    "office": "Antipolo CCPS, Rizal PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2026-04-16",
    "dateDisplay": "April 16, 2026",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Soft Tissue Swelling on Right Elbow and Abrasions on Left Thigh",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "Not Qualified",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on April 23, 2026 (Approved by the NHQ PSF-SFA Committee on May 13, 2026) to receive Php100,000.00 (DILG)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2026-011",
    "type": "WIPO",
    "year": 2026,
    "rank": "Pat",
    "name": "Jonathan Lomibao Tatel",
    "province": "Rizal PPO",
    "office": "Taytay MPS, Rizal PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2026-04-18",
    "dateDisplay": "April 18, 2026",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Bite Mark on Left Hand and Multiple Abrasion on Left Elbow and Left Forearm",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "For recommendation",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on April 27, 2026 (Approved by the NHQ PSF-SFA Committee on May 13, 2026) to receive Php100,000.00 (DILG)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2026-012",
    "type": "WIPO",
    "year": 2026,
    "rank": "Pat",
    "name": "Jomarie Callejo Abrazaldo",
    "province": "Rizal PPO",
    "office": "Taytay MPS, Rizal PPO, PRO 4A",
    "stage": "Benefits Processing",
    "status": "In Process",
    "date": "2026-04-18",
    "dateDisplay": "April 18, 2026",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Abrasions on Right and Left Hand",
    "benefits": {
      "rhe": "Out Patient",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "For recommendation",
      "psmbfi": "Not Eligible",
      "psfSfa": "Submitted documentary requirements to MWD, DPRM on April 27, 2026 (Approved by the NHQ PSF-SFA Committee on May 13, 2026) to receive Php100,000.00 (DILG)",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan"
    }
  },
  {
    "id": "WIPO-2026-013",
    "type": "WIPO",
    "year": 2026,
    "rank": "Patrolman",
    "name": "Mark Brayan S Dadulla",
    "province": "RHQ",
    "office": "RPDEU 4A",
    "stage": "Document Completion",
    "status": "Pending",
    "date": "2026-07-08",
    "dateDisplay": "July 8 2026",
    "sourceCoverage": "As of July 6, 2026",
    "injury": "Gunshot Wound (Abdomen)",
    "benefits": {
      "rhe": "Confined at Perpetual Help Medical Center-Biñan Brgy. Sto Niño, Biñan City, Laguna",
      "specialPromotion": "Not Recommended",
      "awards": "Not Eligible",
      "scholarship": "For recommendation",
      "psmbfi": "Not Eligible",
      "psfSfa": "For completion of documentary requirements",
      "others": "Php5,000.00 from PRO 4A Lakas Tulungan PSMBFI 20,000"
    }
  }
];
