// Generated from the CY 2025 and CY 2026 compulsory retiree workbooks.
// Contact numbers are intentionally excluded from the public website.
export const retireeRecords = [
  {
    "id": "RET-2025-001",
    "year": 2025,
    "rank": "PCMS",
    "name": "Arnaldo Sotto Rico",
    "retirementDate": "2025-01-01",
    "retirementDisplay": "January 01, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "Requirements were already submitted to PRBs dated February 20, 2025",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-002",
    "year": 2025,
    "rank": "PSMS",
    "name": "Rogelio Timbang Contado",
    "retirementDate": "2025-01-11",
    "retirementDisplay": "January 11, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "Already submitted his CAL Folder & LUMPSUM last January 27, 2025 at PRBS",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-003",
    "year": 2025,
    "rank": "PCPT",
    "name": "REYMUNDO PALOMA PINAWIN",
    "retirementDate": "2025-01-17",
    "retirementDisplay": "January 17, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "Submitted folders for CAL at PRBs on October 16, 2024, Lumpsum submitted on December 9, 2024",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-004",
    "year": 2025,
    "rank": "PCMS",
    "name": "Alfonso Flores Capistrano",
    "retirementDate": "2025-01-23",
    "retirementDisplay": "January 23, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "Already submitted his CAL folder on December 4, 2024 at PRBS & OUTRIGHT Folder submitted on January 6, 2025.",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-005",
    "year": 2025,
    "rank": "NUP",
    "name": "Tarcila Badion Bataller",
    "retirementDate": "2025-01-31",
    "retirementDisplay": "January 31, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "Already submitted his CAL Folder last March 7, 2025 at PRBS",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-006",
    "year": 2025,
    "rank": "PEMS",
    "name": "Marissa Legaspi De Castro",
    "retirementDate": "2025-02-14",
    "retirementDisplay": "February 14, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL and Lumpsum Folders forwarded to PRBS dated February 12, 2025",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-007",
    "year": 2025,
    "rank": "PLTCOL",
    "name": "NOEMAN ABA-EO CAS-OY",
    "retirementDate": "2025-02-27",
    "retirementDisplay": "February 27, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Folder already submitted on February 10, 2025 and LUMP SUM folder already submitted on February 11, 2025 at PRBS",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-008",
    "year": 2025,
    "rank": "PCpl",
    "name": "Ernesto Libico Urrutia",
    "retirementDate": "2025-02-28",
    "retirementDisplay": "February 28, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "Already submitted his CAL Folder & LUMPSUM last January 27, 2025 at PRBS",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-009",
    "year": 2025,
    "rank": "PMAJ",
    "name": "GERRY SOLOMON ABALOS",
    "retirementDate": "2025-03-04",
    "retirementDisplay": "March 04, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "Already submitted his CAL Folder last January 31, 2025 at PRBS",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-010",
    "year": 2025,
    "rank": "PMSg",
    "name": "Eve Cristobal Lodripas",
    "retirementDate": "2025-04-06",
    "retirementDisplay": "April 06, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL and Lump Sum requirements were already submitted to PRBU.",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-011",
    "year": 2025,
    "rank": "PEMS",
    "name": "Excelsis Rosario Zamora",
    "retirementDate": "2025-04-25",
    "retirementDisplay": "April 25, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL and Lump Outright pension December 18, 2025 were already submitted to PRBU.",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-012",
    "year": 2025,
    "rank": "NUP",
    "name": "Virginia Evangelista Ranillo",
    "retirementDate": "2025-05-30",
    "retirementDisplay": "May 30, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Folders forwarded to PRBS dated February 12, 2025",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-013",
    "year": 2025,
    "rank": "PEMS",
    "name": "Gene Miran Eugenio",
    "retirementDate": "2025-05-30",
    "retirementDisplay": "May 30, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Folder & LUMPSUM last May 5, 2025 at PRBS",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-014",
    "year": 2025,
    "rank": "PMAJ",
    "name": "FLORENTE DOBLUIS YU",
    "retirementDate": "2025-05-31",
    "retirementDisplay": "May 31, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Folder & LUMPSUM last June 26, 2025 at PRBS",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-015",
    "year": 2025,
    "rank": "PMAJ",
    "name": "EDWARD BAUTISTA CANTANO",
    "retirementDate": "2025-06-22",
    "retirementDisplay": "June 22, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL and Lump Sum requirements for were already submitted dated July 7, 2025",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-016",
    "year": 2025,
    "rank": "PEMS",
    "name": "Nomer Soriaga Flores",
    "retirementDate": "2025-07-05",
    "retirementDisplay": "July 05, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "Said PNCO submitted his CAL Folder & LUMPSUM last May 16, 2025 at PRBS",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-017",
    "year": 2025,
    "rank": "PSMS",
    "name": "Sancho Aquino Marasigan",
    "retirementDate": "2025-07-08",
    "retirementDisplay": "July 08, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL and Outright pension requirements for were already submitted dated September 24, 2025",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-018",
    "year": 2025,
    "rank": "PCAPT",
    "name": "CARMEN GARCIA BALILO",
    "retirementDate": "2025-07-16",
    "retirementDisplay": "July 16, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Folder forwarded to mPRBS April 17, 2025 & LUMP SUM folder already submitted on Nov 23, 2025 at PRBU.",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-019",
    "year": 2025,
    "rank": "PEMS",
    "name": "Laurence Ngan-noy Tayaban",
    "retirementDate": "2025-07-18",
    "retirementDisplay": "July 18, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "Said PNCO submitted his CAL Folder & LUMPSUM last April 4, 2025 at PRBS 4A",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-020",
    "year": 2025,
    "rank": "PLTCOL",
    "name": "PAULITO MACASA SABULAO",
    "retirementDate": "2025-08-10",
    "retirementDisplay": "August 10, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Folder & LUMP SUM folder already submitted on May 14, 2025 at PRBU.",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-021",
    "year": 2025,
    "rank": "PEMS",
    "name": "Rolando Hernandez Galicia",
    "retirementDate": "2025-08-25",
    "retirementDisplay": "August 25, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Foldewr and Lumpsum uploaded his requirements last August 28, 2025",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-022",
    "year": 2025,
    "rank": "PLT",
    "name": "NOEL TUMAMAO GAMIAO",
    "retirementDate": "2025-08-29",
    "retirementDisplay": "August 29, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Foldewr and Lumpsum uploaded his requirements last August 22, 2025",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-023",
    "year": 2025,
    "rank": "PSSg",
    "name": "Gil Ermita Lopez",
    "retirementDate": "2025-09-01",
    "retirementDisplay": "September 01, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Folder Uploaded October 29, 2025 and Lumpsum uploaded Nov 4, 2025",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-024",
    "year": 2025,
    "rank": "PLT",
    "name": "RODELIO ESCAVILLAS HALINA",
    "retirementDate": "2025-09-09",
    "retirementDisplay": "September 09, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Folder & LUMP SUM folder already submitted on July 21, 2025 at PRBS.",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-025",
    "year": 2025,
    "rank": "PCPT",
    "name": "DANTE MOJARES BAUTISTA",
    "retirementDate": "2025-09-14",
    "retirementDisplay": "September 14, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Folder & LUMP SUM folderforwarded to PRBS on July 5, 2025",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-026",
    "year": 2025,
    "rank": "PEMS",
    "name": "Ernesto Rey Sangcap",
    "retirementDate": "2025-09-24",
    "retirementDisplay": "September 24, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Foldewr and Lumpsum uploaded his requirements last September 4, 2025",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-027",
    "year": 2025,
    "rank": "PLT",
    "name": "GERMAN ALLUNAR MERLE",
    "retirementDate": "2025-10-11",
    "retirementDisplay": "October 11, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Foldewr and Lumpsum uploaded his requirements last September 29, 2025",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-028",
    "year": 2025,
    "rank": "PCMS",
    "name": "Joselito Almeyda Caparroso",
    "retirementDate": "2025-10-16",
    "retirementDisplay": "October 16, 2025",
    "calRequirements": "Lost of issued FA 38 revolver smith and weason since 2005",
    "lumpSumRequirements": "Not indicated",
    "status": "Lacking Requirements",
    "remarks": "No remarks indicated",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-029",
    "year": 2025,
    "rank": "PCPT",
    "name": "DANNY AMBAGAN FERRERA",
    "retirementDate": "2025-10-26",
    "retirementDisplay": "October 26, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Folder uploaded his requirements last July 07, 2025,",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-030",
    "year": 2025,
    "rank": "PEMS",
    "name": "Moses Valde Abastilla",
    "retirementDate": "2025-10-30",
    "retirementDisplay": "October 30, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "Said PNCO uploaded his requirements last August 11, 2025, and also submitted his CAL and OUTRIGHT Folders on the same date.",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-031",
    "year": 2025,
    "rank": "PSSg",
    "name": "Joel Mirafelix Balajadia",
    "retirementDate": "2025-11-09",
    "retirementDisplay": "November 09, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Folder & LUMP SUM folderforwarded to PRBS on July 23, 2025",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-032",
    "year": 2025,
    "rank": "PMAJ",
    "name": "ALEJANDRO DY ONQUIT",
    "retirementDate": "2025-11-26",
    "retirementDisplay": "November 26, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Folder & LUMP SUM folderforwarded to PRBS on December 26, 2025",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-033",
    "year": 2025,
    "rank": "PCMS",
    "name": "Bienvenido Adrados Bernales",
    "retirementDate": "2025-12-01",
    "retirementDisplay": "December 01, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Folder & LUMP SUM folderforwarded to PRBS on December 4, 2025",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-034",
    "year": 2025,
    "rank": "PCpl",
    "name": "Casiano Erni Rosas",
    "retirementDate": "2025-12-02",
    "retirementDisplay": "December 02, 2025",
    "calRequirements": "Complete requirements",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Folder & LUMP SUM folderforwarded to PRBU4A on August 27, 2025",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-035",
    "year": 2025,
    "rank": "NUP",
    "name": "George Meren Ladiana",
    "retirementDate": "2025-12-08",
    "retirementDisplay": "December 08, 2025",
    "calRequirements": "PPO Clearance",
    "lumpSumRequirements": "Not indicated",
    "status": "Pending Clearance",
    "remarks": "Waiting for the release of clearance",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-036",
    "year": 2025,
    "rank": "PEMS",
    "name": "Geraldine Gantong Oriondo",
    "retirementDate": "2025-12-16",
    "retirementDisplay": "December 16, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Folder & LUMP SUM folderforwarded to PRBU4A on September 10, 2025",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2025-037",
    "year": 2025,
    "rank": "PEMS",
    "name": "Eduardo Fabrea Rallos",
    "retirementDate": "2025-12-27",
    "retirementDisplay": "December 27, 2025",
    "calRequirements": "COMPLETE",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "No remarks indicated",
    "sourceCoverage": "CY 2025"
  },
  {
    "id": "RET-2026-001",
    "year": 2026,
    "rank": "PLT",
    "name": "FELICIDAD KATIPUNAN CORNEJO",
    "retirementDate": "2026-01-02",
    "retirementDisplay": "January 02, 2026",
    "calRequirements": "Complete",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "Said PNCO uploaded his requirements last August 15, 2025 and also submitted his CAL Claims and Lump-Sum Claims forwarded to PRBU 4A August 20, 2025.",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-002",
    "year": 2026,
    "rank": "PSMS",
    "name": "Merlito Pineda Maraquilla",
    "retirementDate": "2026-01-12",
    "retirementDisplay": "January 12, 2026",
    "calRequirements": "PPO Clearance RSAO Clearance NAPOLCOM Clearance DC Clearance DL Clearance",
    "lumpSumRequirements": "PPO CLearance RSAO Clearance DC Clearance DL Clearance OMBUDSMAN Clearance",
    "status": "Pending Clearance",
    "remarks": "Waiting for the release of clearance",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-003",
    "year": 2026,
    "rank": "PMSg",
    "name": "Romeo Moriente Mojica",
    "retirementDate": "2026-01-19",
    "retirementDisplay": "January 19, 2026",
    "calRequirements": "Complete",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Claims and Lump-Sum Claims Already forwarded to PRBU 4A on February 18, 2026",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-004",
    "year": 2026,
    "rank": "PLTCOL",
    "name": "RADAM REYES RAMOS",
    "retirementDate": "2026-01-21",
    "retirementDisplay": "January 21, 2026",
    "calRequirements": "Complete",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Claims and Lump-Sum Claims Already forwarded to PRBU 4A on November 22, 2025",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-005",
    "year": 2026,
    "rank": "PCPT",
    "name": "ALLAN ESTRECHO DESEMBRANA",
    "retirementDate": "2026-01-30",
    "retirementDisplay": "January 30, 2026",
    "calRequirements": "Complete",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Claims andLump-Sum Claims Already forwarded to PRBU 4A on Jan 30, 2026",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-006",
    "year": 2026,
    "rank": "PLT",
    "name": "FERDINAND PEÑASCOSAS LARROSA",
    "retirementDate": "2026-02-03",
    "retirementDisplay": "February 03, 2026",
    "calRequirements": "Complete",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "Said PCO submitted his CAL Claims and Lump-Sum Claims Forwarded to last December 5, 2025.",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-007",
    "year": 2026,
    "rank": "PCPT",
    "name": "RODIRIC AQUINO SANVICTORES",
    "retirementDate": "2026-02-04",
    "retirementDisplay": "February 04, 2026",
    "calRequirements": "Complete",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Claims and Lump-Sum Claims Already forwarded to PRBU 4A on February 27, 2026",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-008",
    "year": 2026,
    "rank": "PCPT",
    "name": "REYNANTE GARCIA DE CHAVEZ",
    "retirementDate": "2026-02-15",
    "retirementDisplay": "February 15, 2026",
    "calRequirements": "Complete",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Claims and Lump-Sum Claims Already forwarded to PRBU 4A on November 25, 2026",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-009",
    "year": 2026,
    "rank": "PLT",
    "name": "NELSON VILLANUEVA FLORES",
    "retirementDate": "2026-02-22",
    "retirementDisplay": "February 22, 2026",
    "calRequirements": "Complete",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Claims and Lump-Sum Claims Already forwarded to PRBU 4A on January 19, 2025",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-010",
    "year": 2026,
    "rank": "PSMS",
    "name": "Richard Fermil",
    "retirementDate": "2026-02-25",
    "retirementDisplay": "February 25, 2026",
    "calRequirements": "Complete",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Claims and Outright Already forwarded to PRBU 4A on April 7, 2026",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-011",
    "year": 2026,
    "rank": "PLT",
    "name": "RUEL MARTINEZ CANTOS",
    "retirementDate": "2026-03-03",
    "retirementDisplay": "March 03, 2026",
    "calRequirements": "Complete",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Claims and Lump-Sum Claims Forwarded to PRBU 4A dated February 6, 2026",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-012",
    "year": 2026,
    "rank": "NUP",
    "name": "Felicidad Alpuerto Febrer",
    "retirementDate": "2026-03-07",
    "retirementDisplay": "March 07, 2026",
    "calRequirements": "Complete",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Claims Forwarded to PRBU 4A dated October 29, 2025",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-013",
    "year": 2026,
    "rank": "NUP",
    "name": "Gary Abad Garbino",
    "retirementDate": "2026-03-07",
    "retirementDisplay": "March 07, 2026",
    "calRequirements": "Complete",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Claims Forwarded to PRBU 4A dated January 8, 2026",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-014",
    "year": 2026,
    "rank": "PEMS",
    "name": "Gregorio Casalme Maunahan",
    "retirementDate": "2026-03-12",
    "retirementDisplay": "March 12, 2026",
    "calRequirements": "Complete",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Claims and Lump-Sum Claims Forwarded to PRBU 4A dated March 11, 2026",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-015",
    "year": 2026,
    "rank": "PCpl",
    "name": "Candido Bascara Arobinto",
    "retirementDate": "2026-03-21",
    "retirementDisplay": "March 21, 2026",
    "calRequirements": "DL Clearance",
    "lumpSumRequirements": "Complete",
    "status": "Lacking Requirements",
    "remarks": "Already forwarded to PRBS on July 8, 2026",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-016",
    "year": 2026,
    "rank": "PEMS",
    "name": "Gregorio Gonzales Cuevas",
    "retirementDate": "2026-03-28",
    "retirementDisplay": "March 28, 2026",
    "calRequirements": "Complete",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL and LUMPSUM Already forwarded to PRBU 4A on February 2, 2026",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-017",
    "year": 2026,
    "rank": "PEMS",
    "name": "Benedict Mabao Dela Cruz",
    "retirementDate": "2026-03-28",
    "retirementDisplay": "March 28, 2026",
    "calRequirements": "Complete",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL and LUMPSUM Already forwarded to PRBU 4A on February 27, 2026",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-018",
    "year": 2026,
    "rank": "PEMS",
    "name": "Lyndel Curia Inolpe",
    "retirementDate": "2026-04-09",
    "retirementDisplay": "April 09, 2026",
    "calRequirements": "Complete",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL and Outright Pension Already forwarded to PRBU 4A on April 22, 2026",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-019",
    "year": 2026,
    "rank": "PEMS",
    "name": "Wenefredo Labaclado Jacla",
    "retirementDate": "2026-04-09",
    "retirementDisplay": "April 09, 2026",
    "calRequirements": "Complete",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Claims and Lump-Sum Claims Already forwarded to PRBU 4A on May 5, 2026",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-020",
    "year": 2026,
    "rank": "PEMS",
    "name": "Ronaldo Laguerta Abadilla",
    "retirementDate": "2026-05-05",
    "retirementDisplay": "May 05, 2026",
    "calRequirements": "DL Clearance",
    "lumpSumRequirements": "DL Clearance",
    "status": "Pending Clearance",
    "remarks": "Waiting for the release of clearance",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-021",
    "year": 2026,
    "rank": "PSMS",
    "name": "Ricky Manzanero Gonzales",
    "retirementDate": "2026-05-18",
    "retirementDisplay": "May 18, 2026",
    "calRequirements": "Under BOS",
    "lumpSumRequirements": "Not indicated",
    "status": "Under BOS",
    "remarks": "Waiting for the release of clearance",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-022",
    "year": 2026,
    "rank": "PSSg",
    "name": "Edilberto Reposo Hilvano",
    "retirementDate": "2026-05-24",
    "retirementDisplay": "May 24, 2026",
    "calRequirements": "Complete",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "CAL Claims and Lump-Sum Claims Already forwarded to PRBU 4A on February 27, 2026",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-023",
    "year": 2026,
    "rank": "Pat",
    "name": "Donald Silva Moratalla",
    "retirementDate": "2026-06-03",
    "retirementDisplay": "June 03, 2026",
    "calRequirements": "RSAO Clearance NAPOLCOM CLearance DC Clearance DL Clearance",
    "lumpSumRequirements": "PPO CLearance RSAO Clearance DC Clearance DL Clearance OMBUDSMAN Clearance",
    "status": "Pending Clearance",
    "remarks": "Waiting for the release of clearance",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-024",
    "year": 2026,
    "rank": "PLT",
    "name": "RIZALINA GARRA MANALO",
    "retirementDate": "2026-06-19",
    "retirementDisplay": "June 19, 2026",
    "calRequirements": "NAPOLCOM Clearance DL Clearance,",
    "lumpSumRequirements": "NAPOLCOM Clearance DL Clearance OMBUDSMAN Clearance.",
    "status": "Pending Clearance",
    "remarks": "Waiting for the release of clearance",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-025",
    "year": 2026,
    "rank": "PCMS",
    "name": "Galo Abelardo Dapat Beraña",
    "retirementDate": "2026-07-01",
    "retirementDisplay": "July 01, 2026",
    "calRequirements": "RSAO Clearance NAPOLCOM CLearance DC Clearance DL Clearance",
    "lumpSumRequirements": "PPO CLearance RSAO Clearance DC Clearance DL Clearance OMBUDSMAN Clearance",
    "status": "Pending Clearance",
    "remarks": "Waiting for the release of clearance",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-026",
    "year": 2026,
    "rank": "PSSg",
    "name": "Rogelio Doniña Garin",
    "retirementDate": "2026-07-07",
    "retirementDisplay": "July 07, 2026",
    "calRequirements": "RSAO Clearance NAPOLCOM CLearance DC Clearance DL Clearance",
    "lumpSumRequirements": "PPO CLearance RSAO Clearance DC Clearance DL Clearance OMBUDSMAN Clearance",
    "status": "Pending Clearance",
    "remarks": "Waiting for the release of clearance",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-027",
    "year": 2026,
    "rank": "PBGEN",
    "name": "HANSEL MATAMIS MARANTAN",
    "retirementDate": "2026-07-10",
    "retirementDisplay": "July 10, 2026",
    "calRequirements": "Not indicated",
    "lumpSumRequirements": "Not indicated",
    "status": "Pending Clearance",
    "remarks": "Waiting for the release of clearance",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-028",
    "year": 2026,
    "rank": "PMAJ",
    "name": "EDGAR FERRER FABREGAS",
    "retirementDate": "2026-07-14",
    "retirementDisplay": "July 14, 2026",
    "calRequirements": "PPO CLearance RSAO Clearance DC Clearance DL Clearance",
    "lumpSumRequirements": "PPO CLearance RSAO Clearance DC Clearance DL Clearance OMBUDSMAN Clearance",
    "status": "Pending Clearance",
    "remarks": "Waiting for the release of clearance",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-029",
    "year": 2026,
    "rank": "PSMS",
    "name": "Garry Cruzat Guerra",
    "retirementDate": "2026-07-15",
    "retirementDisplay": "July 15, 2026",
    "calRequirements": "Completed",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "For endorsement to PRBU 4A",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-030",
    "year": 2026,
    "rank": "PMAJ",
    "name": "JULIO GURRA DOGTA",
    "retirementDate": "2026-07-25",
    "retirementDisplay": "July 25, 2026",
    "calRequirements": "Completed",
    "lumpSumRequirements": "Not indicated",
    "status": "Complete",
    "remarks": "For endorsement to PRBU 4A",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-031",
    "year": 2026,
    "rank": "PLT",
    "name": "RANDY LAGUNSIN DELIM",
    "retirementDate": "2026-08-10",
    "retirementDisplay": "August 10, 2026",
    "calRequirements": "RSAO Clearance NAPOLCOM CLearance DC Clearance DL Clearance",
    "lumpSumRequirements": "PPO CLearance RSAO Clearance DC Clearance DL Clearance OMBUDSMAN Clearance",
    "status": "Pending Clearance",
    "remarks": "Waiting for the release of clearance",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-032",
    "year": 2026,
    "rank": "PLT",
    "name": "EDGARDO MALABANAN MANARIN",
    "retirementDate": "2026-08-31",
    "retirementDisplay": "August 31, 2026",
    "calRequirements": "RSAO Clearance NAPOLCOM CLearance DC Clearance DL Clearance",
    "lumpSumRequirements": "PPO CLearance RSAO Clearance DC Clearance DL Clearance OMBUDSMAN Clearance",
    "status": "Pending Clearance",
    "remarks": "Waiting for the release of clearance",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-033",
    "year": 2026,
    "rank": "PEMS",
    "name": "Paquito Enriquez Chan",
    "retirementDate": "2026-08-30",
    "retirementDisplay": "August 30, 2026",
    "calRequirements": "RSAO Clearance NAPOLCOM CLearance DC Clearance DL Clearance",
    "lumpSumRequirements": "PPO CLearance RSAO Clearance DC Clearance DL Clearance OMBUDSMAN Clearance",
    "status": "Pending Clearance",
    "remarks": "Waiting for the release of clearance",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-034",
    "year": 2026,
    "rank": "PSMS",
    "name": "Herminio Eugenio Mauricio",
    "retirementDate": "2026-09-16",
    "retirementDisplay": "September 16, 2026",
    "calRequirements": "RSAO Clearance NAPOLCOM CLearance DC Clearance DL Clearance",
    "lumpSumRequirements": "PPO CLearance RSAO Clearance DC Clearance DL Clearance OMBUDSMAN Clearance",
    "status": "Pending Clearance",
    "remarks": "Waiting for the release of clearance",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-035",
    "year": 2026,
    "rank": "PSMS",
    "name": "Maximo Hugo Villoso, Jr",
    "retirementDate": "2026-10-30",
    "retirementDisplay": "October 30, 2026",
    "calRequirements": "RSAO Clearance NAPOLCOM CLearance DC Clearance DL Clearance",
    "lumpSumRequirements": "PPO CLearance RSAO Clearance DC Clearance DL Clearance OMBUDSMAN Clearance",
    "status": "Pending Clearance",
    "remarks": "Waiting for the release of clearance",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-036",
    "year": 2026,
    "rank": "PLT",
    "name": "TEODORO LABITAG PADUA",
    "retirementDate": "2026-11-03",
    "retirementDisplay": "November 03, 2026",
    "calRequirements": "PPO CLearance RSAO Clearance DC Clearance DL Clearance OMBUDSMAN Clearance",
    "lumpSumRequirements": "PPO CLearance RSAO Clearance DC Clearance DL Clearance OMBUDSMAN Clearance",
    "status": "Pending Clearance",
    "remarks": "Waiting for the release of clearance",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-037",
    "year": 2026,
    "rank": "PLT",
    "name": "FLORENCIO RUANTO SARMIENTO",
    "retirementDate": "2026-11-07",
    "retirementDisplay": "November 07, 2026",
    "calRequirements": "RSAO Clearance NAPOLCOM CLearance DC Clearance DL Clearance",
    "lumpSumRequirements": "PPO CLearance RSAO Clearance DC Clearance DL Clearance OMBUDSMAN Clearance",
    "status": "Pending Clearance",
    "remarks": "Waiting for the release of clearance",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-038",
    "year": 2026,
    "rank": "PEMS",
    "name": "Edgardo Cablao Gallardo",
    "retirementDate": "2026-11-30",
    "retirementDisplay": "November 30, 2026",
    "calRequirements": "RSAO Clearance NAPOLCOM CLearance DC Clearance DL Clearance",
    "lumpSumRequirements": "PPO CLearance RSAO Clearance DC Clearance DL Clearance OMBUDSMAN Clearance",
    "status": "Pending Clearance",
    "remarks": "Waiting for the release of clearance",
    "sourceCoverage": "As of July 15, 2026"
  },
  {
    "id": "RET-2026-039",
    "year": 2026,
    "rank": "PLT",
    "name": "RONALDO GONZALES GLORIOSO",
    "retirementDate": "2026-12-11",
    "retirementDisplay": "December 11, 2026",
    "calRequirements": "RSAO Clearance NAPOLCOM CLearance DC Clearance DL Clearance",
    "lumpSumRequirements": "PPO CLearance RSAO Clearance DC Clearance DL Clearance OMBUDSMAN Clearance",
    "status": "Pending Clearance",
    "remarks": "Waiting for the release of clearance",
    "sourceCoverage": "As of July 15, 2026"
  }
];
