// Generated from the user-provided RHE.xlsx workbook.
// The records are intentionally isolated from the existing KIPO/WIPO and retirees data modules.

export type RheRecord = {
  id: string;
  year: 2025 | 2026;
  sourceNo: number | string;
  name: string;
  unitAssignment: string;
  diagnosis: string;
  procedureDone: string;
  hospital: string;
  dateOfConfinement: string;
  category: string;
  amount: number;
  dateApproved: string;
  dateApprovedDisplay: string;
  remarks: string;
};

export const rheRecords: RheRecord[] = [
  {
    "id": "RHE-2025-001",
    "year": 2025,
    "sourceNo": 1,
    "name": "PCpl Alexander B Leones Jr",
    "unitAssignment": "Lopez MPS, QPPO",
    "diagnosis": "Bronchial Asthma in Acute Exacerbation",
    "procedureDone": "None",
    "hospital": "Calamba Doctor’s Hospital",
    "dateOfConfinement": "September 14-18, 2024",
    "category": "Medical Case",
    "amount": 39693.37,
    "dateApproved": "2025-01-23",
    "dateApprovedDisplay": "January 23, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-002",
    "year": 2025,
    "sourceNo": 2,
    "name": "PCpl Norwendell B Bayan",
    "unitAssignment": "Silang MPS, CPPO",
    "diagnosis": "Right Radius and Ulnar Fracture, multiple abrasions fracture and multiple soft tissue contusion with abrasions",
    "procedureDone": "ORIF of Radius & Ulnar",
    "hospital": "Silang Specialist Medical Center",
    "dateOfConfinement": "May 9-18, 2024",
    "category": "Emergency Surgical case",
    "amount": 100000.0,
    "dateApproved": "2025-01-23",
    "dateApprovedDisplay": "January 23, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-003",
    "year": 2025,
    "sourceNo": 3,
    "name": "PEMS Archie T Alvarado",
    "unitAssignment": "RID/RSOU 4A",
    "diagnosis": "Compression Fracture, Left without neurologic deficit secondary to MVA; S/P ‘E’ Balloon Kyphoplasty L1( C-arm guided)",
    "procedureDone": "Balloon Kyphoplasty L1 vertebrae under GA",
    "hospital": "PNPGH ORTHO WARD",
    "dateOfConfinement": "May 31-June 8, 2024",
    "category": "Surgical Case (Major)",
    "amount": 100000.0,
    "dateApproved": "2025-01-23",
    "dateApprovedDisplay": "January 23, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-004",
    "year": 2025,
    "sourceNo": 4,
    "name": "NUP Anne E Razo",
    "unitAssignment": "San Andres MPS, QPPO",
    "diagnosis": "Dengue Fever with no warning signs, Hypertension, Type 2 Diabetes Mellitus and UTI",
    "procedureDone": "None",
    "hospital": "Lucena United Doctor’s Hospital and Medical Clinic",
    "dateOfConfinement": "August 2-6, 2024",
    "category": "Medial Emergency Case",
    "amount": 27768.39,
    "dateApproved": "2025-01-23",
    "dateApprovedDisplay": "January 23, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-005",
    "year": 2025,
    "sourceNo": 5,
    "name": "NUP Cherrie Lyn B Baylon",
    "unitAssignment": "San Mateo MPS, RPPO",
    "diagnosis": "Acute Calculous Cholecystitis",
    "procedureDone": "S/P Laparoscopic Subtotal Cholecystectomy",
    "hospital": "Jose R Reyes Memorial Medical Center",
    "dateOfConfinement": "July 16-20, 2024",
    "category": "Surgical Case (Major)",
    "amount": 97467.1,
    "dateApproved": "2025-01-23",
    "dateApprovedDisplay": "January 23, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-006",
    "year": 2025,
    "sourceNo": 6,
    "name": "Pat Hudson G Caag",
    "unitAssignment": "Calaca MPS, BPPO",
    "diagnosis": "Tuberculosis Arthritis, Left Knee",
    "procedureDone": "Arthroscopic Synovectomy Arthroscopic Menisectomy Arthroscopic Abrasion Chondroplasty Left Knee",
    "hospital": "Mary Mediatrix Medical Center, Lipa City, Batangas",
    "dateOfConfinement": "September 10-12, 2024",
    "category": "Surgical Case (Major)",
    "amount": 100000.0,
    "dateApproved": "2025-01-23",
    "dateApprovedDisplay": "January 23, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-007",
    "year": 2025,
    "sourceNo": 7,
    "name": "PCPT NICANOR A MICOSA",
    "unitAssignment": "Tanauan MPS, BPPO",
    "diagnosis": "LRTI,UTI, Vascular Headache, Benign Paroxysmal Vertigo, Hypertension and Acute Bronchitis",
    "procedureDone": "None",
    "hospital": "Healthway Daniel O. Mercado Medical Center",
    "dateOfConfinement": "November 15-18, 2024",
    "category": "Medical Case",
    "amount": 17576.63,
    "dateApproved": "2025-01-23",
    "dateApprovedDisplay": "January 23, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-008",
    "year": 2025,
    "sourceNo": 8,
    "name": "PLT ROSSANA B NACAR",
    "unitAssignment": "RCSU 4A",
    "diagnosis": "Abnormal Uterine bleeding probably secondary to Endomentrial Polyp, Anemia secondary to blood loss",
    "procedureDone": "Exploratory Laparotomy",
    "hospital": "Global Care Medical Center of Canlubang",
    "dateOfConfinement": "August 28-31, 2024",
    "category": "Surgical Case (Major)",
    "amount": 100000.0,
    "dateApproved": "2025-01-23",
    "dateApprovedDisplay": "January 23, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-009",
    "year": 2025,
    "sourceNo": 9,
    "name": "PCpl Christian C Cacao",
    "unitAssignment": "Talisay MPS, BPPO",
    "diagnosis": "Fracture, closed, complete, Proximal Humerus (R )",
    "procedureDone": "S/P ORIF- Plating Proximal Humerus, ®",
    "hospital": "Sta. Ana Hospital, Manila",
    "dateOfConfinement": "August 13-15, 2024",
    "category": "Surgical Case (Major)",
    "amount": 100000.0,
    "dateApproved": "2025-01-23",
    "dateApprovedDisplay": "January 23, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-010",
    "year": 2025,
    "sourceNo": 10,
    "name": "NUP Jocelyn D Bautista",
    "unitAssignment": "RLRDD",
    "diagnosis": "Community Acquired Pneumonia High Risk; Acute Pulmonary Edema; Acute Hypoxemic Respiratory Failure Status Post Intubation",
    "procedureDone": "None",
    "hospital": "Calamba Medical Center",
    "dateOfConfinement": "August 22 - September 12, 2024",
    "category": "Medial Emergency Case",
    "amount": 240250.0,
    "dateApproved": "2025-01-23",
    "dateApprovedDisplay": "January 23, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-011",
    "year": 2025,
    "sourceNo": 11,
    "name": "PCpl Jascelle Joy S Monteverde",
    "unitAssignment": "Mauban MPS, QPPO",
    "diagnosis": "Breast Cancer(R), S/P 8th cycle Chemotherapy",
    "procedureDone": "S/P Mastectomy Right Breast",
    "hospital": "Lucena MMG General Hospital",
    "dateOfConfinement": "September 23-27, 2024",
    "category": "Catastrophic Case",
    "amount": 85338.12,
    "dateApproved": "2025-04-28",
    "dateApprovedDisplay": "April 28, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-012",
    "year": 2025,
    "sourceNo": 12,
    "name": "PMAJ ROBIN L MARTIN",
    "unitAssignment": "Tanauan City PS, BPPO",
    "diagnosis": "Extensor Muscle and Tendon Transection Secondary to Hackwound, Left Forearm",
    "procedureDone": "Wound Exploration; Primary Repair of Extensor Muscles and Tendons, Left Forearm",
    "hospital": "Tanauan Medical Center",
    "dateOfConfinement": "October 4-7, 2024",
    "category": "WIPO Case",
    "amount": 60233.4,
    "dateApproved": "2025-04-28",
    "dateApprovedDisplay": "April 28, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-013",
    "year": 2025,
    "sourceNo": 13,
    "name": "Pat Chino F Rosario (+)",
    "unitAssignment": "SOU 4A, PDEG",
    "diagnosis": "Colon Cancer Stage IV",
    "procedureDone": "Exploratory Laparotomy, takedown of colostomy, re-anastomosis of ileum segments end-to-end, double barrel colostomy",
    "hospital": "Medical Center Manila, Manila",
    "dateOfConfinement": "July 16- August 8, 2024; August 10-September 12, 2024",
    "category": "Catastrophic Case",
    "amount": 269500.0,
    "dateApproved": "2025-04-28",
    "dateApprovedDisplay": "April 28, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-014",
    "year": 2025,
    "sourceNo": 14,
    "name": "PSSg Johnston M Alacre",
    "unitAssignment": "RPPO Antipolo CCPS-BCP",
    "diagnosis": "Mid face Fracture Le Fort type III, Bilateral Secondary to MVA",
    "procedureDone": "Open treatment of craniofacial separation",
    "hospital": "Chinese General Hospital and Medical Center",
    "dateOfConfinement": "November 1-19, 2024",
    "category": "WIPO Case",
    "amount": 490724.8,
    "dateApproved": "2025-04-28",
    "dateApprovedDisplay": "April 28, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-015",
    "year": 2025,
    "sourceNo": 15,
    "name": "PEMS Ryan D Rada",
    "unitAssignment": "Calamba CCPS, LPPO",
    "diagnosis": "ACS STEMI",
    "procedureDone": "Angiogram",
    "hospital": "Global Care Medical Center of Canlubang; PNPGH-MMW; and Philippine Heart Center",
    "dateOfConfinement": "November 25- December 6, 2024",
    "category": "Catastrophic Case",
    "amount": 70453.71,
    "dateApproved": "2025-04-28",
    "dateApprovedDisplay": "April 28, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-016",
    "year": 2025,
    "sourceNo": 16,
    "name": "PMSg Marry Ann Broncano",
    "unitAssignment": "PIDMU, LPPO",
    "diagnosis": "Hypertension Stage 2, sec. to Headache Left Maxillary Sinusitis",
    "procedureDone": "None",
    "hospital": "Laguna Holy Family Hospital, Inc",
    "dateOfConfinement": "October 30- November 11, 2024",
    "category": "Medical Case",
    "amount": 60000.0,
    "dateApproved": "2025-04-28",
    "dateApprovedDisplay": "April 28, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-017",
    "year": 2025,
    "sourceNo": 17,
    "name": "NUP Virgleen A Delgado",
    "unitAssignment": "Angono MPS, RPPO",
    "diagnosis": "Peri Anal Abscess",
    "procedureDone": "S/P Wound Debridement",
    "hospital": "Lucban MMG Hospital",
    "dateOfConfinement": "October 16-19, 2024",
    "category": "Surgical Minor",
    "amount": 50530.08,
    "dateApproved": "2025-04-28",
    "dateApprovedDisplay": "April 28, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-018",
    "year": 2025,
    "sourceNo": 18,
    "name": "PCOL JULIUS C SURIBEN",
    "unitAssignment": "OCRS, RHQ",
    "diagnosis": "LGIB sec to bleeding external hemorrhoids; IRON DEFICIENCY ANEMIA",
    "procedureDone": "Colonoscopy",
    "hospital": "Capitol Medical Center, Inc",
    "dateOfConfinement": "June 13-18, 2025",
    "category": "Surgical Case (Major)",
    "amount": 149633.02,
    "dateApproved": "2025-08-07",
    "dateApprovedDisplay": "August 7, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-019",
    "year": 2025,
    "sourceNo": 19,
    "name": "PLTCOL ALFREDO E DULAY JR",
    "unitAssignment": "OCRS, RHQ",
    "diagnosis": "Herpes Zoster",
    "procedureDone": "None",
    "hospital": "St. Luke’s Medical Center",
    "dateOfConfinement": "May 13-18, 2025",
    "category": "Medical Case",
    "amount": 80245.73,
    "dateApproved": "2025-08-07",
    "dateApprovedDisplay": "August 7, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-020",
    "year": 2025,
    "sourceNo": 20,
    "name": "PCpl Mark A Abagon",
    "unitAssignment": "Cainta MPS, RPPO",
    "diagnosis": "Penetrating Abdominal Injury secondary to Gunshot wound (8th ICS MCL right, L1-L2 paravertebral right) with Grade II liver Injury segment V; Grade 4 Kidney injury, right",
    "procedureDone": "Exploratory laparotomy, evacuation of Hemoperitoneum, Nephrectomy, right",
    "hospital": "Pasig City General Hospital",
    "dateOfConfinement": "March 12-24, 2025",
    "category": "WIPO Case",
    "amount": 281532.58,
    "dateApproved": "2025-09-08",
    "dateApprovedDisplay": "September 8, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-021",
    "year": 2025,
    "sourceNo": 21,
    "name": "PCPT JOSE V DE LEON",
    "unitAssignment": "RHQ ORPRMD-RPHAS",
    "diagnosis": "Fistula in Ano; complicated pelvirectal abscess; internal helorroids grade I",
    "procedureDone": "S/P Closure of Ano Fistula w/ rectal advancement, incision and drainage of Pelvirectal Abscess",
    "hospital": "Our Lady of Caysasay Medical Center",
    "dateOfConfinement": "January 21-23, 2025",
    "category": "Surgical Case (Minor)",
    "amount": 88000.0,
    "dateApproved": "2025-09-08",
    "dateApprovedDisplay": "September 8, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-022",
    "year": 2025,
    "sourceNo": 22,
    "name": "PLT MA THERESA A ARDANIEL",
    "unitAssignment": "San Mateo MPS, RPPO",
    "diagnosis": "Ovarian new growth, malignant, Intraoperative stage IV-B",
    "procedureDone": "Resection of Ovarian Malignancy with Bilateral Salpingo-Oophorectomy and Omentectomy;   -58950",
    "hospital": "Calamba Medical Center",
    "dateOfConfinement": "February 26- March 2, 2025",
    "category": "Catastrophic Case",
    "amount": 100752.03,
    "dateApproved": "2025-09-08",
    "dateApprovedDisplay": "September 8, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-023",
    "year": 2025,
    "sourceNo": 23,
    "name": "PCMS Eusopher John B Muksan",
    "unitAssignment": "Lipa CCPS, BPPO",
    "diagnosis": "Cellulitis (R), Type 2 DM, Hypertension II & Dyslipidemia",
    "procedureDone": "Wound Debridement, Escharotomy",
    "hospital": "Alaminos Doctor’s Hospital",
    "dateOfConfinement": "January 9-14, 2025",
    "category": "Surgical Case (Minor)",
    "amount": 80132.3,
    "dateApproved": "2025-09-08",
    "dateApprovedDisplay": "September 8, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-024",
    "year": 2025,
    "sourceNo": 24,
    "name": "PCMS Jonnabee P Enriquez",
    "unitAssignment": "San Pascual MPS, BPPO",
    "diagnosis": "Nephrolithiasis, Left",
    "procedureDone": "Extracorporeal Shock Wave Lithotripsy (ESWL)",
    "hospital": "PNPGH/ Manila Lithotripters, Inc",
    "dateOfConfinement": "February 3-4, 2025",
    "category": "Surgical Case (Minor)",
    "amount": 45000.0,
    "dateApproved": "2025-09-08",
    "dateApprovedDisplay": "September 8, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-025",
    "year": 2025,
    "sourceNo": 25,
    "name": "PSMS Gary R Beniga",
    "unitAssignment": "RHPU 4A PHPT QUEZON",
    "diagnosis": "Chronic Kidney Disease, stage 5",
    "procedureDone": "IJ Cathether Insertion",
    "hospital": "St. Anne General Hospital, Inc",
    "dateOfConfinement": "February 9-22, 2025",
    "category": "Catastrophic Case",
    "amount": 67410.45,
    "dateApproved": "2025-09-08",
    "dateApprovedDisplay": "September 8, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-026",
    "year": 2025,
    "sourceNo": 26,
    "name": "PMSg Lorenzo P Almaceda",
    "unitAssignment": "San Pablo CCPS, LPPO",
    "diagnosis": "Renal Cell Carcinoma left; Complete gut obstruction secondary to post operative adhesions and Hyperactive Cardiovascular Disease",
    "procedureDone": "Radical Nephrectomy, left;  Appendectomy",
    "hospital": "Global Medical Center of Laguna",
    "dateOfConfinement": "January 25 – March 1, 2025",
    "category": "Catastrophic Case",
    "amount": 339250.0,
    "dateApproved": "2025-09-08",
    "dateApprovedDisplay": "September 8, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-027",
    "year": 2025,
    "sourceNo": 27,
    "name": "PMSg Emery T Navalta",
    "unitAssignment": "PCADU QPPO",
    "diagnosis": "Hypertensive Urgency, Hypertension essential s2, uncontrolled",
    "procedureDone": "None",
    "hospital": "Mount Carmel Diocesan General Hospital, Lucena City, QUezon",
    "dateOfConfinement": "March 3-5, 2025",
    "category": "Emergency Medical Case",
    "amount": 10545.7,
    "dateApproved": "2025-09-08",
    "dateApprovedDisplay": "September 8, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-028",
    "year": 2025,
    "sourceNo": 28,
    "name": "PSSg Eric M Alteza",
    "unitAssignment": "San Luis MPS, BPPO",
    "diagnosis": "Gangrenous Gall bladder; Cholelithiasis with Choledocholithiasis",
    "procedureDone": "S/P Open Cholecystectomy + JP drain",
    "hospital": "Metro Lemery Medical Center",
    "dateOfConfinement": "March 12-26, 2025",
    "category": "Emergency Surgical Case (Major)",
    "amount": 100000.0,
    "dateApproved": "2025-09-08",
    "dateApprovedDisplay": "September 8, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-029",
    "year": 2025,
    "sourceNo": 29,
    "name": "PSSg Charina D Madelar",
    "unitAssignment": "PCADU, QPPO",
    "diagnosis": "CVA Bleed, Status Post Craniectomy Evacuation of ICH, Respiratory Failure, Status Post Tracheostomy; Acute Fronto Temporal Right, Status Post Emergency Craniectomy Evacuation of Ich; Acute Respiratory Failure; Complicated Urinary Tract Infection; Dysphagia Secondary to CVA, Status to CVA, Status Post Insertion",
    "procedureDone": "Decompressive Hemicraniectomy right: Evacuation of ICH right",
    "hospital": "Mount Carmel Diocesan General Hospital",
    "dateOfConfinement": "February 11- April 3, 2025",
    "category": "Catastrophic Case",
    "amount": 350000.0,
    "dateApproved": "2025-09-08",
    "dateApprovedDisplay": "September 8, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-030",
    "year": 2025,
    "sourceNo": 30,
    "name": "Pat Mary Grace J Dorado",
    "unitAssignment": "Nagcarlan MPS, LPPO",
    "diagnosis": "Ruptured Appendicitis",
    "procedureDone": "S/P Appendectomy, drain",
    "hospital": "Laguna Doctor’s Hospital, Inc",
    "dateOfConfinement": "February 10-13, 2025",
    "category": "Emergency Surgical Major",
    "amount": 68892.71,
    "dateApproved": "2025-09-08",
    "dateApprovedDisplay": "September 8, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-031",
    "year": 2025,
    "sourceNo": 31,
    "name": "PSSg German D Makahiya",
    "unitAssignment": "PIU-PSOU, Laguna PPO",
    "diagnosis": "Fracture, Open 3S, Complete, Comminuted, Lateral Malleolus Right secondary to Gunshot",
    "procedureDone": "Status Post   Open Reduction and Internal Fixation (ORIF) Plating Lateral Malleolus Right",
    "hospital": "PNP-GH",
    "dateOfConfinement": "March 4-25, 2025",
    "category": "WIPO",
    "amount": 98000.0,
    "dateApproved": "2025-09-15",
    "dateApprovedDisplay": "September 15, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-032",
    "year": 2025,
    "sourceNo": 32,
    "name": "PEMS Shernan N Malelang",
    "unitAssignment": "PNG-Maritime Group RMU 4A",
    "diagnosis": "Hypertensive and Arteriosclerotic Cardiovascular Disease (HASCVD), ACS STEMI ANTEROSEPTAL WALL KILIP I TIMI2 SEVERE 2V CAD; T/C   LEFT VENTRICULAR (LV) THROMBUS",
    "procedureDone": "S/P Coronary Angiogram + Percutaneous coronary intervention",
    "hospital": "University of Perpetual Help Delta Medical Center (Private)",
    "dateOfConfinement": "December 19-22, 2024",
    "category": "Catastrophic Cse",
    "amount": 128796.25,
    "dateApproved": "2025-09-15",
    "dateApprovedDisplay": "September 15, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-033",
    "year": 2025,
    "sourceNo": 33,
    "name": "PMAJ CHARLIE M REYES",
    "unitAssignment": "Cuenca MPS, BPPO",
    "diagnosis": "Hypertension",
    "procedureDone": "None",
    "hospital": "Taal Polymedic Hospital and Medical Center, Batangas (Private)",
    "dateOfConfinement": "December 20-21, 2024",
    "category": "Medical Case",
    "amount": 23632.9,
    "dateApproved": "2025-09-15",
    "dateApprovedDisplay": "September 15, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-034",
    "year": 2025,
    "sourceNo": 34,
    "name": "PSMS Romeo N Contreras",
    "unitAssignment": "Santo Tomas City Police Station, BPO",
    "diagnosis": "Urinary Bladder Neoplasm Probably Malignant",
    "procedureDone": "Cystoscopy, Resection of Bladder Tumor",
    "hospital": "St. Frances Cabrini Medical Center, Batangas (Private)",
    "dateOfConfinement": "November 6-8, 2024",
    "category": "Surgical Case (Major)",
    "amount": 100000.0,
    "dateApproved": "2025-09-15",
    "dateApprovedDisplay": "September 15, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-035",
    "year": 2025,
    "sourceNo": 35,
    "name": "PEMS Arnold C Ardon",
    "unitAssignment": "Regional Legal Office 4A",
    "diagnosis": "Peptic Ulcer Disease",
    "procedureDone": "EsophagoGastro Duodenoscopy",
    "hospital": "Calamba Medical Center, Laguna (Private)",
    "dateOfConfinement": "December 13-14, 2024",
    "category": "Surgical Case (Minor)",
    "amount": 38252.17,
    "dateApproved": "2025-09-15",
    "dateApprovedDisplay": "September 15, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-036",
    "year": 2025,
    "sourceNo": 36,
    "name": "Pat Albert Glen R Abiog",
    "unitAssignment": "Tanza MPS, Cavite PPO",
    "diagnosis": "Acute Cholecystitis with Cholecystolithiasis",
    "procedureDone": "Open Cholecystectomy with Intraoperative Cholangiogram",
    "hospital": "PNP-GH",
    "dateOfConfinement": "October 22- November 11, 2024",
    "category": "Surgical Case (Major)",
    "amount": 35152.0,
    "dateApproved": "2025-09-15",
    "dateApprovedDisplay": "September 15, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-037",
    "year": 2025,
    "sourceNo": 37,
    "name": "PSMS Jose F Bernabe",
    "unitAssignment": "Atimonan MPS, QPPO",
    "diagnosis": "Acute Appendicitis Gangrenous",
    "procedureDone": "Appendectomy",
    "hospital": "Rakkk Prophet Medical Center, Quezon (Private)",
    "dateOfConfinement": "November 15-18, 2024",
    "category": "Surgical Case (Major",
    "amount": 76478.19,
    "dateApproved": "2025-09-15",
    "dateApprovedDisplay": "September 15, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-038",
    "year": 2025,
    "sourceNo": 38,
    "name": "PSMS Rodel P Gulifardo",
    "unitAssignment": "Padre Burgos MPS, QPPO",
    "diagnosis": "Acute Appendicitis",
    "procedureDone": "Open Appendectomy",
    "hospital": "Lucena Medical Mission Group General Hospital (Private",
    "dateOfConfinement": "October 26-29, 2024",
    "category": "Surgical Case (Major)",
    "amount": 84138.6,
    "dateApproved": "2025-09-15",
    "dateApprovedDisplay": "September 15, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-039",
    "year": 2025,
    "sourceNo": 39,
    "name": "PLTCOL BISMARK S MENDOZA",
    "unitAssignment": "PARMU- Logistics, CPPO",
    "diagnosis": "Upper I Bleeding secondary to H. Pylori",
    "procedureDone": "Colonoscopy and EGD",
    "hospital": "PNPGH and Delos Santos Medical Center",
    "dateOfConfinement": "April 22-23, 2025",
    "category": "Surgical Case (Minor)",
    "amount": 36832.0,
    "dateApproved": "2025-09-15",
    "dateApprovedDisplay": "September 15, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-040",
    "year": 2025,
    "sourceNo": 40,
    "name": "PCMS Noriel Kristoffer J Afuang",
    "unitAssignment": "OPD, LPPO",
    "diagnosis": "Urgency Hypertensive, Non ST-elevation Acute Coronary Syndrome",
    "procedureDone": "None",
    "hospital": "Los Banos Doctor’s Hospital and Medical Center, Inc",
    "dateOfConfinement": "November 5-7, 2024",
    "category": "Medical Emergencyl Case",
    "amount": 27490.0,
    "dateApproved": "2025-09-29",
    "dateApprovedDisplay": "September 29, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-041",
    "year": 2025,
    "sourceNo": 41,
    "name": "PSSg Ferdinand L Paz",
    "unitAssignment": "RHQ ORHSU",
    "diagnosis": "Orchitis, right",
    "procedureDone": "None",
    "hospital": "St. James Hospital, Inc., Sta. Rosa, Laguna",
    "dateOfConfinement": "December 26-29, 2024",
    "category": "Medical Case",
    "amount": 38066.3,
    "dateApproved": "2025-09-29",
    "dateApprovedDisplay": "September 29, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-042",
    "year": 2025,
    "sourceNo": 42,
    "name": "PEMS Raquelyn S Tadique",
    "unitAssignment": "Siniloan MPS, LPPO",
    "diagnosis": "Breast Carcinoma, right",
    "procedureDone": "Modified Radical Mastectomy, right drain",
    "hospital": "Laguna Holy Family Hospital, Inc., Sta. Cruz, Laguna",
    "dateOfConfinement": "February 4-6, 2025",
    "category": "Surgical Case",
    "amount": 55840.0,
    "dateApproved": "2025-09-29",
    "dateApprovedDisplay": "September 29, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-043",
    "year": 2025,
    "sourceNo": 43,
    "name": "PCMS Annalyn Miano Dres",
    "unitAssignment": "PARMU, LPPO",
    "diagnosis": "Endometrial Intraepithelial Neoplasi",
    "procedureDone": "TAHBSO (Total Abdominal                            Hysterectomy with Bilateral Salpingo-oophorectomy)",
    "hospital": "Binakayan Hospital and Medical",
    "dateOfConfinement": "March 27-31, 2025",
    "category": "Surgical Case",
    "amount": 96131.85,
    "dateApproved": "2025-09-29",
    "dateApprovedDisplay": "September 29, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-044",
    "year": 2025,
    "sourceNo": 44,
    "name": "Pat Florida Amangan Bagyon",
    "unitAssignment": "Bay MPS, LPPO",
    "diagnosis": "Tuberculosis of Lung; Trapped Lung Left secondary to ruptured infected pneumatacele",
    "procedureDone": "Left Lateral Open Thoractomy Dulectomy, decortication and deloculation",
    "hospital": "Philippine Heart Center",
    "dateOfConfinement": "February 22 to March 8, 2025",
    "category": "Surgical Case",
    "amount": 78755.0,
    "dateApproved": "2025-09-29",
    "dateApprovedDisplay": "September 29, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-045",
    "year": 2025,
    "sourceNo": 45,
    "name": "PCpl Wilbert V Fernandez",
    "unitAssignment": "PIU, LPPO",
    "diagnosis": "Fracture, closed, comminuted, displaced, clavicle left",
    "procedureDone": "ORIF (Locked plate) Clavicle, left",
    "hospital": "PNPGH, Camp Crame, QC",
    "dateOfConfinement": "February 21- March 7, 2025",
    "category": "Surgical Case",
    "amount": 59340.0,
    "dateApproved": "2025-09-29",
    "dateApprovedDisplay": "September 29, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-046",
    "year": 2025,
    "sourceNo": 46,
    "name": "PCpl Ariel B Deomampo",
    "unitAssignment": "Talisay MPS, BPPO",
    "diagnosis": "Calculous Cholecystitis",
    "procedureDone": "Open Cholecystectomy",
    "hospital": "Metro Lemery Medical Center",
    "dateOfConfinement": "March 23-25, 2025",
    "category": "Surgical Case",
    "amount": 88112.15,
    "dateApproved": "2025-09-29",
    "dateApprovedDisplay": "September 29, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-047",
    "year": 2025,
    "sourceNo": 47,
    "name": ". Pat Mark Anthony M Bathan",
    "unitAssignment": "Tanauan CCPS, BPPO",
    "diagnosis": "Multiple Physical Injuries secondary to Vehicular Crash, Femoral Shaft Fracture, right",
    "procedureDone": "S/P ORIF-Intramedullary Nailing Right Femur + ORIF- Tension Band Suturing Right Patella",
    "hospital": "Healthway Medical Network and PNP-GH",
    "dateOfConfinement": "June 15-30, 2025",
    "category": "WIPO",
    "amount": 184861.8,
    "dateApproved": "2025-11-04",
    "dateApprovedDisplay": "November 4, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-048",
    "year": 2025,
    "sourceNo": 48,
    "name": "PSSg Rogelio B Narvasa Jr (+)",
    "unitAssignment": "1st PMFC, BPPO",
    "diagnosis": "Community Acquired Pneumonia moderate risk, Chronic Obstructive Pulmonary Disease, to consider CNS Infection, Type II DM, Dyslipidemia, Squamous Cell Carcinoma, Lung",
    "procedureDone": "CT Scan guided Fine Needle Aspiration Biopsy of Left Upper Lobe Mass with Rapid Paps",
    "hospital": "Mary Mediatrix Medical Center,Lipa City, Batangas",
    "dateOfConfinement": "March 11-20, 2025; April 11-21, 2025",
    "category": "Catastopic Case",
    "amount": 335050.0,
    "dateApproved": "2025-11-04",
    "dateApprovedDisplay": "November 4, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-049",
    "year": 2025,
    "sourceNo": 49,
    "name": "PEMS Claro B Ganceña Jr",
    "unitAssignment": "Biñan CPS, LPPO",
    "diagnosis": "Upper Gastrointestinal Bleeding secondary to Gastric Ulcers",
    "procedureDone": "Esophagogastroduodenoscopy",
    "hospital": "Calamba Doctor’s Hospital",
    "dateOfConfinement": "April 21-23, 2025",
    "category": "Surgical Case",
    "amount": 100000.0,
    "dateApproved": "2025-11-04",
    "dateApprovedDisplay": "November 4, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-050",
    "year": 2025,
    "sourceNo": 50,
    "name": "PSSg Joy Anafe L Magda",
    "unitAssignment": "PIDMU, LPPO",
    "diagnosis": "Hydrops of the Gallbladder",
    "procedureDone": "Open Cholecystectomy",
    "hospital": "St. Jude Family Hospital Inc., Laguna",
    "dateOfConfinement": "May 14-19, 2025",
    "category": "Surgical Case",
    "amount": 57739.2,
    "dateApproved": "2025-11-04",
    "dateApprovedDisplay": "November 4, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-051",
    "year": 2025,
    "sourceNo": 51,
    "name": "PCMS Jerry C Malto",
    "unitAssignment": "PARMU HQS, CPPO",
    "diagnosis": "Sepsis secondary to Diabetic foot, Left with Osteomyelitis, Type II DM and Uncontrolled Hypertension Stage II",
    "procedureDone": "Wound Debridement, Ray amputation, 5th digit foot",
    "hospital": "Binakayan Hospital and Medical Center, Kawit, Cavite",
    "dateOfConfinement": "May 20-28, 2025",
    "category": "Surgical Case",
    "amount": 100000.0,
    "dateApproved": "2025-11-04",
    "dateApprovedDisplay": "November 4, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-052",
    "year": 2025,
    "sourceNo": 52,
    "name": "PCpl John Mark M Oroncillo",
    "unitAssignment": "Tanauan CPS, BPPO",
    "diagnosis": "Acute Suppurative Appendicitis",
    "procedureDone": "Appendectomy; Peritoneal Lavage",
    "hospital": "Tanauan Medical Center",
    "dateOfConfinement": "June 3-6, 2025",
    "category": "Surgical Case",
    "amount": 100000.0,
    "dateApproved": "2025-11-04",
    "dateApprovedDisplay": "November 4, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-053",
    "year": 2025,
    "sourceNo": 53,
    "name": "PSMS Niel Angelo L Macalintal",
    "unitAssignment": "Jalajala MPS, RPPO",
    "diagnosis": "Dengue Fever with warning signs",
    "procedureDone": "None",
    "hospital": "TriCity Medical Hospital, Maybunga, Pasig City",
    "dateOfConfinement": "June 7-12, 2025",
    "category": "Medical Case",
    "amount": 60000.0,
    "dateApproved": "2025-11-04",
    "dateApprovedDisplay": "November 4, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-054",
    "year": 2025,
    "sourceNo": 54,
    "name": "PCMS Alona A Ayaton",
    "unitAssignment": "Lopez MPS, QPPO",
    "diagnosis": "Multiple Cholelithiasis",
    "procedureDone": "Open Cholecystectomy",
    "hospital": "Lucena Medical Mission Group General Hospital",
    "dateOfConfinement": "March 8-13, 2025",
    "category": "Surgical Case",
    "amount": 100000.0,
    "dateApproved": "2025-11-04",
    "dateApprovedDisplay": "November 4, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-055",
    "year": 2025,
    "sourceNo": 55,
    "name": "PSMS Anabel G Colagong",
    "unitAssignment": "RHQ ORIDMD",
    "diagnosis": "Abnormal Uterine Bleeding, Multiple Myona Uteri, Ovarian New Growth, Left, Probably Benign, Probably Endometriotic Cyst, Status Post Enterolysis, Total Abdominal Hysterectomy with Bilateral Salpingo-Oophorectomy under combined Spinal Epidural Anesthesia; Status post Blood Transfusion of 5 Units Pack Red Blood Cell",
    "procedureDone": "Enterolysis, TAHBSO under Combined Spinal Epidural Anesthesia",
    "hospital": "St. Jude Family Hospital Inc., Laguna",
    "dateOfConfinement": "January 5-9, 2025",
    "category": "Surgical Case",
    "amount": 100000.0,
    "dateApproved": "2025-11-04",
    "dateApprovedDisplay": "November 4, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-056",
    "year": 2025,
    "sourceNo": 56,
    "name": "Pat Prince C Asiman",
    "unitAssignment": "Dasmariñas CCPS, CPPO",
    "diagnosis": "Acute Calculous Cholecystitis",
    "procedureDone": "Laparoscopic Cholecystectomy",
    "hospital": "De La Salle University Medical Center",
    "dateOfConfinement": "June 24 -27, 2025",
    "category": "Surgical Case",
    "amount": 100000.0,
    "dateApproved": "2025-11-04",
    "dateApprovedDisplay": "November 4, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-057",
    "year": 2025,
    "sourceNo": 57,
    "name": "PMSg Roald M Distajo",
    "unitAssignment": "PIU PHQ, LPPO",
    "diagnosis": "Nephrolithiasis, Left",
    "procedureDone": "Extracorporeal Shock Wave Lithotripsy (ESWL)",
    "hospital": "PNPGH/ Manila Lithotripters, Inc.",
    "dateOfConfinement": "June 26-27, 2025",
    "category": "Surgical Case",
    "amount": 45000.0,
    "dateApproved": "2025-11-04",
    "dateApprovedDisplay": "November 4, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2025-058",
    "year": 2025,
    "sourceNo": 58,
    "name": "PCMS Domenic C Garcela",
    "unitAssignment": "PARMU-GSO, QPPO",
    "diagnosis": "Congestive Heart Failure and Dilated Cardiomyopathy; Paroxysmal atrial Fibrillation and Acute Gastritis; Coronary Artery Disease",
    "procedureDone": "S/P Coronary Angiogram with Coronary Angioplasty with 1 stent deployed",
    "hospital": "Philippine Heart Center",
    "dateOfConfinement": "November 29-December 2, 2024; December 4, 2024; December 7-16, 2024",
    "category": "Catastrophic Case",
    "amount": 175300.0,
    "dateApproved": "2025-11-04",
    "dateApprovedDisplay": "November 4, 2025",
    "remarks": ""
  },
  {
    "id": "RHE-2026-001",
    "year": 2026,
    "sourceNo": 1,
    "name": "PCPT MANUEL B MADLANGBAYAN",
    "unitAssignment": "Imus HQS, CPPO",
    "diagnosis": "Coronary Artery Disease",
    "procedureDone": "Angioplasty (CAD 2VD, Prox-mid LAD, CTO late, Prox LCX)",
    "hospital": "St. Luke’s Medical Center, Quezon City",
    "dateOfConfinement": "May 15-17, 2025",
    "category": "Catastrophic Case",
    "amount": 118678.06,
    "dateApproved": "2026-01-21",
    "dateApprovedDisplay": "January 21, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-002",
    "year": 2026,
    "sourceNo": 2,
    "name": "PCMS Louie R Santiago",
    "unitAssignment": "1st PMFC, QPPO",
    "diagnosis": "Complex Fistula in Ano",
    "procedureDone": "Colonoscopy, Internal Hemorrhoids, Fistula in Ano, Fistulectomy",
    "hospital": "Metropolitan Medical Center, Manila",
    "dateOfConfinement": "May 1-4, 2025",
    "category": "Surgical Case (Minor)",
    "amount": 64098.96,
    "dateApproved": "2026-01-21",
    "dateApprovedDisplay": "January 21, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-003",
    "year": 2026,
    "sourceNo": 3,
    "name": "PMAJ EDGAR F FABREGAS",
    "unitAssignment": "Batangas CCPS, BPPO",
    "diagnosis": "Gunshot Wound, Point of Entry Epigastric Area then Stomach 2 Points Perforating the Diaphragm, Left, 2 points, Point of exit 9th Intercostal Space, Posterior Axillary Injury to Left, Localized Left Chest",
    "procedureDone": "Exploratory Laparotomy, Chest Tube Insertion",
    "hospital": "United Doctors of St. Camillus De Lellis Hospital and Medical Center, Bolbok, Batangas City",
    "dateOfConfinement": "September 30-October 16, 2025",
    "category": "Police Operations Casualty - WIPO",
    "amount": 558745.68,
    "dateApproved": "2026-01-21",
    "dateApprovedDisplay": "January 21, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-004",
    "year": 2026,
    "sourceNo": 4,
    "name": "PSSg Karl Ernest L Fabonan",
    "unitAssignment": "Batangas CCPS, BPPO",
    "diagnosis": "Comminuted Fracture & Laceration, Left Hand (Open Fracture)",
    "procedureDone": "Debridement and Application of External Fixator",
    "hospital": "United Doctors of St. Camillus De Lellis Hospital & Medical Center, Bolbok, Batangas City",
    "dateOfConfinement": "September 30-October 3, 2025",
    "category": "Police Operations Casualty - WIPO",
    "amount": 106209.65,
    "dateApproved": "2026-01-21",
    "dateApprovedDisplay": "January 21, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-005",
    "year": 2026,
    "sourceNo": 5,
    "name": "PSSg  Arven H Ilagan",
    "unitAssignment": "Batangas CCPS, BPPO",
    "diagnosis": "Hypovolemic Shock Secondary to Transection Branchial Artery Left; Hemoperitoneum Secondary to Grade III Gastro Injury; Grade II Liver & Spleen Injury Secondary to Gunshot Wounds",
    "procedureDone": "Exploratory Laparotomy, Wound Exploration, Repair of Transected Brachial Artery, Left",
    "hospital": "United Doctors of St. Camillus De Lellis Hospital & Medical Center, Bolbok, Batangas City",
    "dateOfConfinement": "September 30-October 7, 2025",
    "category": "Police Operations Casualty - WIPO",
    "amount": 446628.19,
    "dateApproved": "2026-01-21",
    "dateApprovedDisplay": "January 21, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-006",
    "year": 2026,
    "sourceNo": 6,
    "name": "PCMS Alberto R Plaza",
    "unitAssignment": "Calamba CCPS, LPPO",
    "diagnosis": "Penetrating Injury Secondary to Gunshot Wound Right Clavicular & Right Scapular Area",
    "procedureDone": "Wound Exploration, Right Thigh Removal of Foreign Body",
    "hospital": "Calamba Medical Center, Calamba City, Laguna",
    "dateOfConfinement": "October 15-18, 2025",
    "category": "Police Operations Casualty - WIPO",
    "amount": 2637.0,
    "dateApproved": "2026-01-21",
    "dateApprovedDisplay": "January 21, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-007",
    "year": 2026,
    "sourceNo": 7,
    "name": "PSSg John G Principe",
    "unitAssignment": "Calamba CCPS, LPPO",
    "diagnosis": "Penetrating Wound with Grade II Injury at Vastus Lateralis Bicep Femoris Secondary to Gunshot Wound, Right Thigh",
    "procedureDone": "Wound Exploration, Right Thigh, Removal of Foreign Body",
    "hospital": "Calamba Medical Center, Calamba City, Laguna",
    "dateOfConfinement": "October 15-17, 2025",
    "category": "Police Operations Casualty - WIPO",
    "amount": 2629.8,
    "dateApproved": "2026-01-21",
    "dateApprovedDisplay": "January 21, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-008",
    "year": 2026,
    "sourceNo": 8,
    "name": "Pat Renson Celestra",
    "unitAssignment": "Cardona MPS, RPPO",
    "diagnosis": "Fracture Post 3rd Tibia, Left",
    "procedureDone": "ORIF (Open Reduction Internal Fixation) Plate & Screw",
    "hospital": "Cainta Municipal Hospital, Rizal",
    "dateOfConfinement": "July 19-23, 2025",
    "category": "Police Operations Casualty - WIPO",
    "amount": 76565.0,
    "dateApproved": "2026-01-21",
    "dateApprovedDisplay": "January 21, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-009",
    "year": 2026,
    "sourceNo": 9,
    "name": "PMSg Anthony Barrameda",
    "unitAssignment": "Antipolo CCPS, RPPO",
    "diagnosis": "Ruptured Appendicitis",
    "procedureDone": "Appendectomy",
    "hospital": "Angono Medical Hospital, Rizal",
    "dateOfConfinement": "July 29- August 4, 2025",
    "category": "Emergency Surgical Case",
    "amount": 98766.5,
    "dateApproved": "2026-01-21",
    "dateApprovedDisplay": "January 21, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-010",
    "year": 2026,
    "sourceNo": 10,
    "name": "PSSg Norie P Aure",
    "unitAssignment": "Magallanes MPS, CPPO",
    "diagnosis": "Ruptured Appendicitis",
    "procedureDone": "Appendectomy",
    "hospital": "Mendez Specialist Medical Center, Cavite",
    "dateOfConfinement": "September 11-15, 2025",
    "category": "Emergency Surgical",
    "amount": 100000.0,
    "dateApproved": "2026-01-21",
    "dateApprovedDisplay": "January 21, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-011",
    "year": 2026,
    "sourceNo": 1,
    "name": "PMAJ CELSO JHUNE D TALAMPAS",
    "unitAssignment": "Cavinti Municipal Police Station (Former)",
    "diagnosis": "Fracture, Closed, Complete, Displaced, Comminuted Lateral Malleolus, Right with Syndesmotic Joint Disruption",
    "procedureDone": "S/P Open Reduction & Internal Fixation (ORIF)- Plating Lateral Malleolus Right with Syndesmotic Joint Trans fixation",
    "hospital": "PNP-GH, Quezon City",
    "dateOfConfinement": "July 9-14, 2025",
    "category": "Surgical Case (Major)",
    "amount": 79928.0,
    "dateApproved": "2026-01-29",
    "dateApprovedDisplay": "January 29, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-012",
    "year": 2026,
    "sourceNo": 2,
    "name": "PEMS Danilo S Salem",
    "unitAssignment": "Laguna 2nd PMFC, Laguna RMFB",
    "diagnosis": "1.ST Elevation Myocardial Infarction 2. Acute Coronary Syndrome- ST Elevation Myocardial Infarction\n(ICD l21.0)",
    "procedureDone": "Coronary Angioplasty Procedure (3 Vessel)",
    "hospital": "Eastern Laguna Medical Hospital Tuhac Famy, Laguna                           2. Cardinal Santos Medical Center  Greenhills City of San Juan",
    "dateOfConfinement": "1. June 24-30, 2025 2. July 11-15, 2025",
    "category": "Catastrophic Case",
    "amount": 171049.5,
    "dateApproved": "2026-01-29",
    "dateApprovedDisplay": "January 29, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-013",
    "year": 2026,
    "sourceNo": 3,
    "name": "PCpl Bryan F Jancinal",
    "unitAssignment": "Rodriguez MPS, Rizal PPO",
    "diagnosis": "Varicocele",
    "procedureDone": "Varicocelectomy Bilateral",
    "hospital": "PNP-GH, Quezon City",
    "dateOfConfinement": "June 23-25, 2025",
    "category": "Surgical Case (Minor)",
    "amount": 35332.0,
    "dateApproved": "2026-01-29",
    "dateApprovedDisplay": "January 29, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-014",
    "year": 2026,
    "sourceNo": 4,
    "name": "PMSg Leo Mar G Alog",
    "unitAssignment": "Batangas CCPS, Batangas PPO",
    "diagnosis": "Scrotal Tuberculosis",
    "procedureDone": "Scrotoplasty, Wide Excision of Scrotum (Right)",
    "hospital": "Batangas Healthcare Specialist Medical Center, Batangas City",
    "dateOfConfinement": "August 11-15, 2025",
    "category": "Surgical Case (Minor)",
    "amount": 71663.0,
    "dateApproved": "2026-01-29",
    "dateApprovedDisplay": "January 29, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-015",
    "year": 2026,
    "sourceNo": 5,
    "name": "PSSg Enrico L Quimbao",
    "unitAssignment": "Imus MPS, Cavite PPO",
    "diagnosis": "Cardiovascular Disease Infarct, Left Corona Radiata & Lentiform Nucleus, Type 2 Diabetes Mellitus, Type 2 Hypertension",
    "procedureDone": "None",
    "hospital": "PNP-GH, Quezon City",
    "dateOfConfinement": "May 29-June 5, 2025",
    "category": "Catastrophic Case",
    "amount": 14528.57,
    "dateApproved": "2026-01-29",
    "dateApprovedDisplay": "January 29, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-016",
    "year": 2026,
    "sourceNo": 6,
    "name": "PSMS Richard P Congreso",
    "unitAssignment": "Sta. Rosa CPS, Laguna PPO",
    "diagnosis": "Ureterolithiasis Left, S/P Extracorporeal Shock Wave Lithotripsy, Left, Community Acquired Pneumonia- Moderate Risk",
    "procedureDone": "Extracorporeal Shockwave Lithotripsy",
    "hospital": "1.First Cabuyao Hospital Medical Center Inc. 2. Laguna Urology Center Inc. Sta Rosa Laguna",
    "dateOfConfinement": "August 21-26, 2025",
    "category": "Surgical Case (Minor)",
    "amount": 100000.0,
    "dateApproved": "2026-01-29",
    "dateApprovedDisplay": "January 29, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-017",
    "year": 2026,
    "sourceNo": 5,
    "name": "Christopher Erwin Bañaga Abellanosa",
    "unitAssignment": "Lopez Municipal Police Station, Quezon",
    "diagnosis": "Cholelithiasis",
    "procedureDone": "Laparoscopic Cholecystectomy",
    "hospital": "Laparoscopic Cholecystectomy",
    "dateOfConfinement": "May 31, 2025 - June 5, 2025",
    "category": "Surgical Case      (Major)",
    "amount": 100000.0,
    "dateApproved": "2026-02-26",
    "dateApprovedDisplay": "February 26, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-018",
    "year": 2026,
    "sourceNo": 7,
    "name": "Pat Mark Angelo Humarang Deomampo",
    "unitAssignment": "Batangas Police Provincial Office",
    "diagnosis": "Severe Acute Pancreatitis, BISAP 3, Restrictive Lung Disease 2; Severe Hypertriglyceridemia",
    "procedureDone": "Utrasound-guided Paracentesis",
    "hospital": "Makati Medical Center",
    "dateOfConfinement": "June 25 - July 12, 2025",
    "category": "Catastrophic Case",
    "amount": 198250.0,
    "dateApproved": "2026-02-26",
    "dateApprovedDisplay": "February 26, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-019",
    "year": 2026,
    "sourceNo": 9,
    "name": "PCpl Cristante T Artajos",
    "unitAssignment": "Antipolo CPS, Rizal PPO",
    "diagnosis": "Lateral Meniscal Tear Left Knee",
    "procedureDone": "Arthroscopic Debridement",
    "hospital": "PNP-GH, Quezon City and Rizal Provincial Hospital System at Brgy. Mambugan Rizal",
    "dateOfConfinement": "June 27-29, 2025",
    "category": "Surgical Case (Minor)",
    "amount": 100000.0,
    "dateApproved": "2026-02-26",
    "dateApprovedDisplay": "February 26, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-020",
    "year": 2026,
    "sourceNo": 10,
    "name": "PSSg Erwin M De Castro",
    "unitAssignment": "Batangas Police Provincial Office, Rosario MPS",
    "diagnosis": "Intracerebral Hemorrhage Right Thalamoganglionic Extension to Right Frontoparietal Area; Acute Respiratory Failure secondary to Central cause; Hypertensive Emergency",
    "procedureDone": "None",
    "hospital": "N.L Villa Medical center",
    "dateOfConfinement": "June 30, 2025 to July 02, 2025",
    "category": "Catastrophic Case",
    "amount": 139000.0,
    "dateApproved": "2026-02-26",
    "dateApprovedDisplay": "February 26, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-021",
    "year": 2026,
    "sourceNo": 11,
    "name": "PSMS Niño Constante M Olivas",
    "unitAssignment": "Rizal HQS, Rizal PPO",
    "diagnosis": "Upper Gastro Intestinal Bleeding, Anemia Secondary to Blood Pressure (Hypertension) & vascular disease/ Disorder; Congenital Heart Disease Secondary to Acute Kidney Disease",
    "procedureDone": "Endoscopy",
    "hospital": "PNP-GH, Quezon City",
    "dateOfConfinement": "August 9-19, 2025",
    "category": "Emergency Surgical Case (Minor)",
    "amount": 25839.0,
    "dateApproved": "2026-02-26",
    "dateApprovedDisplay": "February 26, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-022",
    "year": 2026,
    "sourceNo": 13,
    "name": "PCpl Roger Mhar P Platino",
    "unitAssignment": "Quezon 2nd PMFC, Quezon PPO",
    "diagnosis": "Acute Appendicitis, Gangrenous",
    "procedureDone": "Appendectomy",
    "hospital": "RAKKK Prophet Medical Center Inc. Gumaca, Quezon",
    "dateOfConfinement": "August 14-18, 2025",
    "category": "Surgical Case (Major)",
    "amount": 62666.66,
    "dateApproved": "2026-02-26",
    "dateApprovedDisplay": "February 26, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-023",
    "year": 2026,
    "sourceNo": 14,
    "name": "Late PEMS Jeanet G Fernandez",
    "unitAssignment": "Pro Calabarzon, Regional Headquarters OROD",
    "diagnosis": "Partial GUT Obstruction secondary to Gastric Mass Metastasis",
    "procedureDone": "None",
    "hospital": "Calamba Doctors Hospital",
    "dateOfConfinement": "August 16-19, 2025",
    "category": "Catastrophic Case",
    "amount": 148375.0,
    "dateApproved": "2026-02-26",
    "dateApprovedDisplay": "February 26, 2026",
    "remarks": "Approved (Pending- waiting for Certificate of Legal Beneficiaries from PRBS)"
  },
  {
    "id": "RHE-2026-024",
    "year": 2026,
    "sourceNo": 15,
    "name": "PSSg Jorge Anthony A Letargo",
    "unitAssignment": "Lucena CPS, Quezon PPO",
    "diagnosis": "Multiple Physical Injury Secondary to Vehicular Accident",
    "procedureDone": "None",
    "hospital": "Lucena MMG General Hospital Ibabang Dupay, Lucena City, Quezon",
    "dateOfConfinement": "August 19-27, 2025",
    "category": "Medical Case",
    "amount": 25419.87,
    "dateApproved": "2026-02-26",
    "dateApprovedDisplay": "February 26, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-025",
    "year": 2026,
    "sourceNo": 16,
    "name": "PSMS Aries A Macalindong",
    "unitAssignment": "Batangas CCPS, Batangas PPO",
    "diagnosis": "Acute Gangrenous Appendicitis, Ruptured",
    "procedureDone": "Appendectomy",
    "hospital": "Jesus of Nazareth Hospital Brgy. Gulod  Itaas Batangas City",
    "dateOfConfinement": "August 25-29, 2025",
    "category": "Emergency Surgical Case (Major)",
    "amount": 44336.0,
    "dateApproved": "2026-02-26",
    "dateApprovedDisplay": "February 26, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-026",
    "year": 2026,
    "sourceNo": 18,
    "name": "Late PLT ARNULFO AQUINO MENDOZA III",
    "unitAssignment": "Taytay MPS, Rizal Police Provincial Office",
    "diagnosis": "Herniation Syndrome and Cerebellar Infarct",
    "procedureDone": "Right Frontal URS Insertion Decompressi-ve Suboccipital Craniectomy",
    "hospital": "New Sinai MDI Hospital",
    "dateOfConfinement": "August 26-29, 2025",
    "category": "Surgical Case (Major)",
    "amount": 194500.0,
    "dateApproved": "2026-02-26",
    "dateApprovedDisplay": "February 26, 2026",
    "remarks": "Approved (Pending- waiting for Certificate of Legal Beneficiaries from PRBS)"
  },
  {
    "id": "RHE-2026-027",
    "year": 2026,
    "sourceNo": 20,
    "name": "Pat Mark Joemelle B Lacuesta",
    "unitAssignment": "Batangas City PS, Batangas Police Provincial Office,",
    "diagnosis": "Acute Respiratory Failure secondary to Pneumonia High Risk, Acute Pulmonary Congestion, Chronic Kidney Disease Stage 5 secondary to Chronic   Glomerulonephritis; Valvular Heart Disease",
    "procedureDone": "None",
    "hospital": "Batangas Health Care Hospital Jesus of Nazareth, Barangay Gulod Itaas, Batangas City",
    "dateOfConfinement": "August 27, 2025 to September 11, 2025",
    "category": "Catastrophic Case",
    "amount": 87274.27,
    "dateApproved": "2026-02-26",
    "dateApprovedDisplay": "February 26, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-028",
    "year": 2026,
    "sourceNo": 21,
    "name": "PSMS Randy Gambo Requinto",
    "unitAssignment": "Lopez MPS Quezon Police Provincial Office",
    "diagnosis": "Fracture Closed Complete Displace Radius Left, Hypertension Stage 2, and Radial Shaft Fracture",
    "procedureDone": "Open Treatment of Radial Shaft        Fracture w/ or w/out internal or external fixation",
    "hospital": "RAKKK Prophet Medical Center Inc., Gumaca, Quezon",
    "dateOfConfinement": "August 30 to September 3, 2025",
    "category": "Surgical Case(Major)",
    "amount": 60000.0,
    "dateApproved": "2026-02-26",
    "dateApprovedDisplay": "February 26, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-029",
    "year": 2026,
    "sourceNo": 22,
    "name": "PCMS Marisa V Gaza",
    "unitAssignment": "PRBU 4A, RHQ Camp Vicente P Lim",
    "diagnosis": "G2P2 (200) Pelvic Endometriosis with Bilateral Endometriotic Cyst, Adenomyosis, Menopause for 7 years",
    "procedureDone": "Exploratory Laparotomy Adhesiolysis, Total Hysterectomy with Bilateral Salphingo-Oophorectomy",
    "hospital": "Calamba Medical Center, Laguna",
    "dateOfConfinement": "September 2-6, 2025",
    "category": "Surgical Case (Major)",
    "amount": 100000.0,
    "dateApproved": "2026-02-26",
    "dateApprovedDisplay": "February 26, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-030",
    "year": 2026,
    "sourceNo": 23,
    "name": "PCpl Mark Abner L Masongsong",
    "unitAssignment": "Malvar MPS, Batangas PPO",
    "diagnosis": "Ruptured Appendicitis with Localized Peritonitis",
    "procedureDone": "Exploratory Laparotomy, Appendectomy; Peritoneal  Ruptured Appendicitis with Localized Peritonitis Lavage",
    "hospital": "Healthway Medical Center Tanuan Batangas and PNP-GH, Quezon City",
    "dateOfConfinement": "October 4-14, 2025",
    "category": "Surgical Case (Major)",
    "amount": 41221.0,
    "dateApproved": "2026-02-26",
    "dateApprovedDisplay": "February 26, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-031",
    "year": 2026,
    "sourceNo": 24,
    "name": "PMAJ RODIARD SAGA DELA PEÑA",
    "unitAssignment": "Teresa MPS, Rizal Police Provincial Office",
    "diagnosis": "Staghorn Calculi, left; Nephrolithiasis, Right; S/P        Percutaneous Nephrolithotripsy Left; DJ Stent Insertion,    Bilateral",
    "procedureDone": "Percutaneous Nephrolithotripsy Left; DJ Stent Insertion,    Bilateral",
    "hospital": "Laguna Doctor’s Hospital Inc. Sitio Mapagmahal Brgy.   Pagsawitan, Sta. Cruz, Laguna",
    "dateOfConfinement": "October 8- 13, 2025",
    "category": "Surgical Case (Major)",
    "amount": 100000.0,
    "dateApproved": "2026-02-26",
    "dateApprovedDisplay": "February 26, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-032",
    "year": 2026,
    "sourceNo": 25,
    "name": "PEMS Almer N Veracruz",
    "unitAssignment": "Sariaya MPS, Quezon PPO",
    "diagnosis": "Dengue Fever without Warning Signs, Acute Bronchitis; Dyslipidemia; Urrinary Tract Infection",
    "procedureDone": "None",
    "hospital": "Unihealth Hospital & Medical Center Tayabas, Quezon",
    "dateOfConfinement": "October 12-15, 2025",
    "category": "Medical Case",
    "amount": 40683.88,
    "dateApproved": "2026-02-26",
    "dateApprovedDisplay": "February 26, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-033",
    "year": 2026,
    "sourceNo": 26,
    "name": "PCPT CHRISTIAN REX DE GUZMAN",
    "unitAssignment": "Los Baños MPS, LPPO",
    "diagnosis": "Congestive Heart Failure-Ejection Fraction (EF) Functional Class 2-3 HASCVD; CAP-MR; Acute Pulmonary Congestion",
    "procedureDone": "None",
    "hospital": "Pamana Medical Center National Highway Brgy. Calamba City Laguna",
    "dateOfConfinement": "October 15-19, 2025",
    "category": "Catastrophic Case",
    "amount": 68442.7,
    "dateApproved": "2026-02-26",
    "dateApprovedDisplay": "February 26, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-034",
    "year": 2026,
    "sourceNo": 28,
    "name": "PCMS Ariane O Oblino",
    "unitAssignment": "40 3rd 1st Maneuver Platoon RMFB",
    "diagnosis": "Obstructive Jaundice Secondary to Choledocholithiasis; Acute Calculous Cholecystitis",
    "procedureDone": "Laparoscopic Cholecystectomy, Common Bile Duct Exploration, Choledochotomy, Intraoperative Cholangiopathy",
    "hospital": "St. Frances Cabini Medical Center Inc. Sto. Tomas Batangas",
    "dateOfConfinement": "November 9-13, 2025",
    "category": "Surgical Case (Major)",
    "amount": 100000.0,
    "dateApproved": "2026-02-26",
    "dateApprovedDisplay": "February 26, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-035",
    "year": 2026,
    "sourceNo": 29,
    "name": "PSSg January De Ramos Mendoza",
    "unitAssignment": "Candelaria MPS , Quezon Police Provincial Office",
    "diagnosis": "Brain Herniation, Intraventricular Hemorrhage",
    "procedureDone": "None",
    "hospital": "Peter Paul Medical Center",
    "dateOfConfinement": "December 15-17, 2025",
    "category": "Catastrophic Case",
    "amount": 132461.2,
    "dateApproved": "2026-02-26",
    "dateApprovedDisplay": "February 26, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-036",
    "year": 2026,
    "sourceNo": 3,
    "name": "PSSg Christopher P Soria",
    "unitAssignment": "ORHSU, RHQ, Camp Vicente P Lim",
    "diagnosis": "Coronary Artery Disease of the Left Anterior Descending Artery",
    "procedureDone": "Coronary Angioplasty (1Vessel)",
    "hospital": "Global Care Medical Center of Canlubang and Global Care Medical Center of Bay",
    "dateOfConfinement": "September 7-13, 2025",
    "category": "Catastrophic Case",
    "amount": 68865.9,
    "dateApproved": "2026-03-11",
    "dateApprovedDisplay": "March 11, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-037",
    "year": 2026,
    "sourceNo": 6,
    "name": "PCpl Ian Mar V Aguinaldo",
    "unitAssignment": "Talisay MPS, Batangas PPO",
    "diagnosis": "Ischemic Heart Failure to consider Cardiac Dysrhythmia; Hypertensive, Cardiovascular Disease",
    "procedureDone": "Coronary\n      Angioplasty     (1 Vessel)",
    "hospital": "Global Care Medical Center of Talisay Inc. Batangas City",
    "dateOfConfinement": "October 28-30, 2025",
    "category": "Emergency Medical Case",
    "amount": 53315.36,
    "dateApproved": "2026-03-11",
    "dateApprovedDisplay": "March 11, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-038",
    "year": 2026,
    "sourceNo": 7,
    "name": "PSSg Hilbert M Rios",
    "unitAssignment": "Batangas CCPS, Batangas PPO",
    "diagnosis": "Batangas CCPS, Batangas PPO",
    "procedureDone": "Varicocelectomy, Bilateral Infertility",
    "hospital": "PNP-General Hospital, Camp Bgen Rafael T Crame, Quezon City",
    "dateOfConfinement": "November 4-6, 2025",
    "category": "Surgical Case (Minor)",
    "amount": 22838.21,
    "dateApproved": "2026-03-11",
    "dateApprovedDisplay": "March 11, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-039",
    "year": 2026,
    "sourceNo": 8,
    "name": "PMSg Melanie DV Villaverde",
    "unitAssignment": "Lucban MPS, Quezon PPO",
    "diagnosis": "Iron Deficiency Anemia, Migraine Headache Secondary to Sleep Deviation; Upper Respiratory Tract Infection",
    "procedureDone": "None",
    "hospital": "Mount Carmel Diocesan General Hospital, Quezon Province",
    "dateOfConfinement": "November 13-16, 2025",
    "category": "Emergency Medical Case",
    "amount": 20941.4,
    "dateApproved": "2026-03-11",
    "dateApprovedDisplay": "March 11, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-040",
    "year": 2026,
    "sourceNo": 9,
    "name": "PMSg Sonnie C Caringal",
    "unitAssignment": "Quezon 1st PMFC, QPPO",
    "diagnosis": "Gunshot Wound Flank Left",
    "procedureDone": "Wound Exploration Debridement with Foreign Body Extraction",
    "hospital": "United Candelaria Doctors Inc. Candelaria Quezon",
    "dateOfConfinement": "December 19-22, 2025",
    "category": "WIPO Case",
    "amount": 112267.41,
    "dateApproved": "2026-03-11",
    "dateApprovedDisplay": "March 11, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-041",
    "year": 2026,
    "sourceNo": 10,
    "name": "PCMS Brilliant V Sales",
    "unitAssignment": "Lipa CCPS, Batangas PPO",
    "diagnosis": "Acute Calculous Cholecystitis",
    "procedureDone": "Laparoscopic Cholecystectomy",
    "hospital": "Lipa Medix Medical Center, Batangas City",
    "dateOfConfinement": "December 22, 2025- January 4, 2026",
    "category": "Major Surgical Case",
    "amount": 100000.0,
    "dateApproved": "2026-03-11",
    "dateApprovedDisplay": "March 11, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-042",
    "year": 2026,
    "sourceNo": 11,
    "name": "PSSg Raymund E Bello",
    "unitAssignment": "Tuy MPS, Batangas PPO",
    "diagnosis": "Ischemic Heart Disease; Acute Coronary Syndrome; Non-ST Elevation, Myocardial Infarction",
    "procedureDone": "None",
    "hospital": "Metro Balayan Medical Center, Caloocan, Balayan, Batangas",
    "dateOfConfinement": "January 16-25, 2026",
    "category": "Catastrophic Case",
    "amount": 142000.0,
    "dateApproved": "2026-03-11",
    "dateApprovedDisplay": "March 11, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-043",
    "year": 2026,
    "sourceNo": 1,
    "name": "Pat JohnPaulo D Llarena",
    "unitAssignment": "Balayan MPS, BPPO",
    "diagnosis": "Fracture Open 1 Comminuted M/3rd Tibia Right secondary to RCI",
    "procedureDone": "Fracture Open 1 Comminuted M/3rd Tibia Right secondary to RCI",
    "hospital": "PNP-General Hospital, Camp Bgen Rafael T Crame, Quezon City",
    "dateOfConfinement": "October 20, 2025 to November 22, 2025",
    "category": "Police Operation Casualty – WIPO Case",
    "amount": 75818.0,
    "dateApproved": "2026-04-14",
    "dateApprovedDisplay": "April 14, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-044",
    "year": 2026,
    "sourceNo": 3,
    "name": "Pat Carl Angelo C Dael",
    "unitAssignment": "Laguna PPO, Calamba City PS",
    "diagnosis": "Laceration Right Foot secondary to accident",
    "procedureDone": "Repair or suture of tendon, foot, flexor, single; primary or secondary, w/o graft, each tendon",
    "hospital": "Calamba Medical Center",
    "dateOfConfinement": "Nov 11-25, 2025",
    "category": "WIPO",
    "amount": 22266.0,
    "dateApproved": "2026-04-14",
    "dateApprovedDisplay": "April 14, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-045",
    "year": 2026,
    "sourceNo": 4,
    "name": "Pat kim Kenneth S Averia",
    "unitAssignment": "Quezon PPO, Quezon PMFB",
    "diagnosis": "Gun Shot Wound Left Arm secondary to Schooling Incident",
    "procedureDone": "Wound Exploration with Debridement",
    "hospital": "United Candelaria Doctors Inc.,",
    "dateOfConfinement": "December 19-22, 2025",
    "category": "WIPO",
    "amount": 66334.77,
    "dateApproved": "2026-04-14",
    "dateApprovedDisplay": "April 14, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-046",
    "year": 2026,
    "sourceNo": 5,
    "name": "PCPL Angelo M Guyos",
    "unitAssignment": "Rizal PPO, San Mateo MPS",
    "diagnosis": "Multiple Injuries from Gunshot; wound # 1Dorsal region base of Penis #2 left scrotum #3 Middle third Left Thigh #4 Left Patella; Fracture (complete, displaced)",
    "procedureDone": "Wound Debridement “E” Debridement +  Arthrotomy Left Knee; Removal of Foreign Body; ORIF Cerclage wiring, Left Patella (October 1, 2025)",
    "hospital": "PNP General Hospital",
    "dateOfConfinement": "September 29-October 9, 2025",
    "category": "Surgical Case (Major)",
    "amount": 34144.0,
    "dateApproved": "2026-04-14",
    "dateApprovedDisplay": "April 14, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-047",
    "year": 2026,
    "sourceNo": 9,
    "name": "Pat Jonathan Villado Oja",
    "unitAssignment": "Rizal PPO, Cardona MPS",
    "diagnosis": "Acute Epidural Hematoma, Frontal Right secondary to motor Vehicular Crash",
    "procedureDone": "Acute Epidural Hematoma, Frontal Right secondary to motor Vehicular Crash",
    "hospital": "None",
    "dateOfConfinement": "December 25 to January 06, 2026",
    "category": "Medical Case",
    "amount": 14501.99,
    "dateApproved": "2026-04-14",
    "dateApprovedDisplay": "April 14, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-048",
    "year": 2026,
    "sourceNo": 1,
    "name": "PSSg Marlon H Hubilla",
    "unitAssignment": "Sta. Rosa Component CPS",
    "diagnosis": "Small Bowel Obstruction from Ruptured Appendix with Generalized Peritonitis",
    "procedureDone": "Small Bowel Obstruction from Ruptured Appendix with Generalized Peritonitis",
    "hospital": "PNPGH, Camp Crame, QC",
    "dateOfConfinement": "October 4-14, 2025",
    "category": "Catastrophic Case",
    "amount": 17816.0,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-049",
    "year": 2026,
    "sourceNo": 2,
    "name": "NUP Jessie Jim D Sampaga",
    "unitAssignment": "Padre Garcia MPS, Batangas PPO, Office of the Regional Comptrollership Division",
    "diagnosis": "Obstructive Jaundice Prob Secondary to Choledocholithiasis; Calculous Cholecystitis",
    "procedureDone": "Obstructive Jaundice Prob Secondary to Choledocholithiasis; Calculous Cholecystitis",
    "hospital": "Calamba Doctors Hospital",
    "dateOfConfinement": "October 25-27, 2025",
    "category": "Medical Case",
    "amount": 24260.73,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-050",
    "year": 2026,
    "sourceNo": 6,
    "name": "PSMS Arvelo C Endozo",
    "unitAssignment": "Ibaan MPS, Batangas PPO",
    "diagnosis": "Cystolitholapaxy, Extension of Bladder Neck",
    "procedureDone": "Obstructive Uropathy Secondary to Bladder Neck Stone",
    "hospital": "",
    "dateOfConfinement": "December 5-12, 2025",
    "category": "Surgical Case (Major)",
    "amount": 100000.0,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-051",
    "year": 2026,
    "sourceNo": 8,
    "name": "PMSg Aikee R Genton",
    "unitAssignment": "Quezon PPO, San Andres MPS",
    "diagnosis": "Small Bowel Gangrene secondary to Mesenteric Ischemia/ Mesenteric Vein Thrombosis",
    "procedureDone": "Small Bowel Gangrene secondary to Mesenteric Ischemia/ Mesenteric Vein Thrombosis",
    "hospital": "Lucena United Doctors Hospital",
    "dateOfConfinement": "Nov 6-19, 2025",
    "category": "Catastrophic Case",
    "amount": 276250.0,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-052",
    "year": 2026,
    "sourceNo": 9,
    "name": "PMSg Aikee R Genton",
    "unitAssignment": "Quezon PPO, San Andres MPS",
    "diagnosis": "1. Hypovolemia from Gastrointestinal Loses, short Bowel Syndrome, Cholestasis from rapid weight loss, acute kidney injury secondary to dehydration from GI Losses",
    "procedureDone": "1. Hypovolemia from Gastrointestinal Loses, short Bowel Syndrome, Cholestasis from rapid weight loss, acute kidney injury secondary to dehydration from GI Losses",
    "hospital": "Mount Carmel Diocesan General Hospital",
    "dateOfConfinement": "Dec 1-7, 2025",
    "category": "Catastrophic Case",
    "amount": 4188.0,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-053",
    "year": 2026,
    "sourceNo": 10,
    "name": "PMSg Aikee R Genton",
    "unitAssignment": "Quezon PPO, San Andres MPS",
    "diagnosis": "1. Intracerebral Hemorrhage Right Thalamoganglionic Extension to Right Frontoparietal Area; Acute Respiratory Failure secondary to Central cause; Hypertensive Emergency",
    "procedureDone": "1. Intracerebral Hemorrhage Right Thalamoganglionic Extension to Right Frontoparietal Area; Acute Respiratory Failure secondary to Central cause; Hypertensive Emergency",
    "hospital": "Mount Carmel Diocesan General Hospital",
    "dateOfConfinement": "Dec 14-17, 2025",
    "category": "Catastrophic Case",
    "amount": 2012.31,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-054",
    "year": 2026,
    "sourceNo": 11,
    "name": "PSSg Aldrin M Ladroma",
    "unitAssignment": "Sta. Rosa CPS, Laguna PO",
    "diagnosis": "Congestive Heart Failure secondary to Dilated Cardiomyopathy",
    "procedureDone": "Congestive Heart Failure secondary to Dilated Cardiomyopathy",
    "hospital": "City Medic Emergency Hospital, Sta. Rosa Laguna",
    "dateOfConfinement": "January 6-10, 2026",
    "category": "Catastrophic Case",
    "amount": 97662.58,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-055",
    "year": 2026,
    "sourceNo": 12,
    "name": "PMSg Dominador V Orig Jr",
    "unitAssignment": "Lucena CCPS, Quezon PPO",
    "diagnosis": "Pyogenic Liver Abscess",
    "procedureDone": "Pyogenic Liver Abscess",
    "hospital": "Mount Carmel Diocesan Gen. Hospital, Lucena City, Quezon",
    "dateOfConfinement": "",
    "category": "Emergency Medical Case",
    "amount": 60000.0,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-056",
    "year": 2026,
    "sourceNo": 13,
    "name": "PCMS Shiela Marie C Daňo",
    "unitAssignment": "Agoncillo MPS, Batangas PPO",
    "diagnosis": "Appendicitis, Twisted Fallopian Tube",
    "procedureDone": "Appendicitis, Twisted Fallopian Tube",
    "hospital": "Metro Lemery Medical Center, Lemery, Batangas",
    "dateOfConfinement": "January 15-18, 2026",
    "category": "Emergency Surgical Case (Major)",
    "amount": 100000.0,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-057",
    "year": 2026,
    "sourceNo": 14,
    "name": "PMSg Raymond D Mateo",
    "unitAssignment": "Sta. Rosa CCPS, Laguna PPO",
    "diagnosis": "Central Nervous System Infection; Encephalitis; Status Post Lumbar Tap",
    "procedureDone": "Central Nervous System Infection; Encephalitis; Status Post Lumbar Tap",
    "hospital": "Calamba Medical Center, Laguna",
    "dateOfConfinement": "January 16-26, 2026",
    "category": "Catastrophic Case",
    "amount": 145500.0,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-058",
    "year": 2026,
    "sourceNo": 15,
    "name": "PCMS Jimwel R Lualhati",
    "unitAssignment": "PPPU Batangas PPO",
    "diagnosis": "Cerebrovascular Disease, Acute Cerebrovascular Disease Bleed. Left Basal Ganglia, Hypertension Emergency, Type II Diabetes Mellitus",
    "procedureDone": "Cerebrovascular Disease, Acute Cerebrovascular Disease Bleed. Left Basal Ganglia, Hypertension Emergency, Type II Diabetes Mellitus",
    "hospital": "Batangas Health Care Hospital Jesus of Nazareth, Batangas City, Mary Mediatrix Medical Center,\nLipa City Batangas",
    "dateOfConfinement": "January 25-February 6, 2026",
    "category": "Catastrophic Case",
    "amount": 184000.0,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-059",
    "year": 2026,
    "sourceNo": 16,
    "name": "PCPT JOSELITO B BILUGAN",
    "unitAssignment": "Batangas 1st PMFC, Batangas PPO",
    "diagnosis": "Nephrolithiasis, Bilateral",
    "procedureDone": "Nephrolithiasis, Bilateral",
    "hospital": "PNPGH, Camp Crame, QC",
    "dateOfConfinement": "January 27-30, 2026",
    "category": "Surgical Case (Major)",
    "amount": 80000.0,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-060",
    "year": 2026,
    "sourceNo": 17,
    "name": "PMSg Victor Rizalito Daroy Corpuz",
    "unitAssignment": "1st Batangas PMF Company, 3rd Platoon",
    "diagnosis": "Ruptured Appendicitis with Generalized Peritonitis",
    "procedureDone": "Ruptured Appendicitis with Generalized Peritonitis",
    "hospital": "Lipa Medix Medical Center",
    "dateOfConfinement": "January 27- February 3, 2026",
    "category": "Catastrophic Case",
    "amount": 156250.0,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-061",
    "year": 2026,
    "sourceNo": 20,
    "name": "PSSg Edison Tuyay Palomeno",
    "unitAssignment": "Tanauan City PS,Batangas PPO",
    "diagnosis": "Sepsis secondary to Perianal Abscess, Severe Diabetic Ketoacidosis, and Type II Diabetes Mellitus, Uncontrolled",
    "procedureDone": "Sepsis secondary to Perianal Abscess, Severe Diabetic Ketoacidosis, and Type II Diabetes Mellitus, Uncontrolled",
    "hospital": "Mary Mediatrix Medical Center, Lipa City, Batangas",
    "dateOfConfinement": "February 1-9, 2026",
    "category": "Catastrophic Case",
    "amount": 141410.0,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-062",
    "year": 2026,
    "sourceNo": 21,
    "name": "PSSg Darwin R Quimoyog",
    "unitAssignment": "Lipa CPS, Batangas PPO",
    "diagnosis": "Flame Burns 20% Total Body surface Area Superficial Partial Thickness Deep Partial-Thickness (all extremities perineum head and neck) rule out inhalational Injury",
    "procedureDone": "Flame Burns 20% Total Body surface Area Superficial Partial Thickness Deep Partial-Thickness (all extremities perineum head and neck) rule out inhalational Injury",
    "hospital": "Mary Mediatrix Medical Center, Batangas",
    "dateOfConfinement": "February 1-9, 2026",
    "category": "Emergency Surgical Case (Major)",
    "amount": 7773.05,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-063",
    "year": 2026,
    "sourceNo": 22,
    "name": "PCpl Carlo Barut Ramos",
    "unitAssignment": "Liliw MPS, Laguna PPO",
    "diagnosis": "Acute Ruptured Appendicitis with Generalized Peritonitis",
    "procedureDone": "Acute Ruptured Appendicitis with Generalized Peritonitis",
    "hospital": "Laguna Holy Family Hospital Inc., Sta Cruz, Laguna",
    "dateOfConfinement": "February 8-12, 2026",
    "category": "Catastrophic Case",
    "amount": 86837.13,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-064",
    "year": 2026,
    "sourceNo": 25,
    "name": "PSSg Romeo G Garcia Jr",
    "unitAssignment": "Kawit MPS, Cavite PPO",
    "diagnosis": "Acute Appendicitis",
    "procedureDone": "Acute Appendicitis",
    "hospital": "San Pedro Calungsod Hospital, Kawit, Cavite",
    "dateOfConfinement": "February 14-25, 2026",
    "category": "Surgical Case (Major)",
    "amount": 100000.0,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-065",
    "year": 2026,
    "sourceNo": 26,
    "name": "PSSg John C Marquez Jr",
    "unitAssignment": "Sta. Rosa CCPS, Laguna PPO",
    "diagnosis": "Congestive Heart Failure secondary to Dilated Cardiomyopathy with Thrombus formation; Type 2 Diabetes Mellitus Uncontrolled; Hypertensive Arteriosclerotic Cardiovascular Disease; Urinary Tract Infection",
    "procedureDone": "Congestive Heart Failure secondary to Dilated Cardiomyopathy with Thrombus formation; Type 2 Diabetes Mellitus Uncontrolled; Hypertensive Arteriosclerotic Cardiovascular Disease; Urinary Tract Infection",
    "hospital": "CityMedic Emergency Hospital Corp. Laguna",
    "dateOfConfinement": "February 14-18, 2026",
    "category": "Catastrophic Case",
    "amount": 89348.59,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-066",
    "year": 2026,
    "sourceNo": 27,
    "name": "Pat Mac Lynndon D Pagcaliwangan",
    "unitAssignment": "Regional Mobile Force Battalion, 403rd A Maneuver Company",
    "diagnosis": "Anterior cruciate ligament (ACL) Tear Left Knee",
    "procedureDone": "Anterior cruciate ligament (ACL) Tear Left Knee",
    "hospital": "PNPGH",
    "dateOfConfinement": "February 17-23, 2026",
    "category": "Surgical Case (Major)",
    "amount": 100000.0,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  },
  {
    "id": "RHE-2026-067",
    "year": 2026,
    "sourceNo": 29,
    "name": "PSSg Kimgerley M Oliver",
    "unitAssignment": "Gen Emilio Aguinaldo MPS, Cavite PPO",
    "diagnosis": "ACS NSTEMI (Acute Coronary Syndrome Non-ST-Segment Elevation Myocardial Infarction) HASCVD Severe 3 Vessel CAD in SR FC II Non-alcoholic Fatty liver Disease",
    "procedureDone": "ACS NSTEMI (Acute Coronary Syndrome Non-ST-Segment Elevation Myocardial Infarction) HASCVD Severe 3 Vessel CAD in SR FC II Non-alcoholic Fatty liver Disease",
    "hospital": "Medical Center Manila, Paco, Manila",
    "dateOfConfinement": "February 20-24, 2026",
    "category": "Catastrophic Case",
    "amount": 86840.73,
    "dateApproved": "2026-06-04",
    "dateApprovedDisplay": "June 4, 2026",
    "remarks": ""
  }
];
